#ifndef _SHELL_GRM_H_
#define _SHELL_GRM_H_

#include <stdint.h>
#include <stdbool.h>

#define _ONLY_STATE_TOKEN_	
#include "shell.lex.h"
#undef	_ONLY_STATE_TOKEN_

enum {
	N_complete_command,
	N_list,
	N_linebreak,
	N_and_or,
	N_list_PRIME,
	N_separator_op,
	N_list_PRIME_PRIME,
	N_pipeline,
	N_and_or_PRIME,
	N_and_or_op,
	N_bang_opt,
	N_pipe_sequence,
	N_command,
	N_pipe_sequence_PRIME,
	N_cmd_prefix,
	N_command_suffix,
	N_cmd_suffix_opt,
	N_cmd_suffix,
	N_io_redirect,
	N_cmd_suffix_PRIME,
	N_cmd_prefix_PRIME,
	N_io_number_opt,
	N_io_kind,
	N_io_file,
	N_io_here,
	N_newline_list,
	N_newline_list_PRIME,
};

#define TOTAL_NTER	27

enum {
	P_LHS_Ncomplete_command_RHS_Nlist_Nlinebreak,
	P_LHS_Nlist_RHS_Nand_or_Nlist_PRIME,
	P_LHS_Nlist_PRIME_RHS_Nseparator_op_Nlist_PRIME_PRIME,
	P_LHS_Nlist_PRIME_RHS,
	P_LHS_Nlist_PRIME_PRIME_RHS_Nand_or_Nlist_PRIME,
	P_LHS_Nlist_PRIME_PRIME_RHS,
	P_LHS_Nand_or_RHS_Npipeline_Nand_or_PRIME,
	P_LHS_Nand_or_PRIME_RHS_Nand_or_op_Nlinebreak_Npipeline_Nand_or_PRIME,
	P_LHS_Nand_or_PRIME_RHS,
	P_LHS_Nand_or_op_RHS_TAND_IF,
	P_LHS_Nand_or_op_RHS_TOR_IF,
	P_LHS_Npipeline_RHS_Nbang_opt_Npipe_sequence,
	P_LHS_Nbang_opt_RHS_TBANG,
	P_LHS_Nbang_opt_RHS,
	P_LHS_Npipe_sequence_RHS_Ncommand_Npipe_sequence_PRIME,
	P_LHS_Npipe_sequence_PRIME_RHS_TPIPE_Nlinebreak_Ncommand_Npipe_sequence_PRIME,
	P_LHS_Npipe_sequence_PRIME_RHS,
	P_LHS_Ncommand_RHS_Ncmd_prefix_Ncommand_suffix,
	P_LHS_Ncommand_RHS_TWORD_Ncmd_suffix_opt,
	P_LHS_Ncommand_suffix_RHS_TWORD_Ncmd_suffix_opt,
	P_LHS_Ncommand_suffix_RHS,
	P_LHS_Ncmd_suffix_opt_RHS_Ncmd_suffix,
	P_LHS_Ncmd_suffix_opt_RHS,
	P_LHS_Ncmd_suffix_RHS_Nio_redirect_Ncmd_suffix_PRIME,
	P_LHS_Ncmd_suffix_RHS_TWORD_Ncmd_suffix_PRIME,
	P_LHS_Ncmd_suffix_PRIME_RHS_Nio_redirect_Ncmd_suffix_PRIME,
	P_LHS_Ncmd_suffix_PRIME_RHS_TWORD_Ncmd_suffix_PRIME,
	P_LHS_Ncmd_suffix_PRIME_RHS,
	P_LHS_Ncmd_prefix_RHS_Nio_redirect_Ncmd_prefix_PRIME,
	P_LHS_Ncmd_prefix_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME,
	P_LHS_Ncmd_prefix_PRIME_RHS_Nio_redirect_Ncmd_prefix_PRIME,
	P_LHS_Ncmd_prefix_PRIME_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME,
	P_LHS_Ncmd_prefix_PRIME_RHS,
	P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind,
	P_LHS_Nio_number_opt_RHS_TIO_NUMBER,
	P_LHS_Nio_number_opt_RHS,
	P_LHS_Nio_kind_RHS_Nio_file,
	P_LHS_Nio_kind_RHS_Nio_here,
	P_LHS_Nio_file_RHS_TLESS_TWORD,
	P_LHS_Nio_file_RHS_TLESSAND_TWORD,
	P_LHS_Nio_file_RHS_TGREAT_TWORD,
	P_LHS_Nio_file_RHS_TGREATAND_TWORD,
	P_LHS_Nio_file_RHS_TDGEART_TWORD,
	P_LHS_Nio_file_RHS_TLESSGREAT_TWORD,
	P_LHS_Nio_file_RHS_TCLOBBER_TWORD,
	P_LHS_Nio_here_RHS_TDLESS_TWORD,
	P_LHS_Nio_here_RHS_TDLESSDASH_TWORD,
	P_LHS_Nlinebreak_RHS_Nnewline_list,
	P_LHS_Nlinebreak_RHS,
	P_LHS_Nseparator_op_RHS_TAMPER,
	P_LHS_Nseparator_op_RHS_TSEMI,
	P_LHS_Nnewline_list_RHS_TNEWLINE_Nnewline_list_PRIME,
	P_LHS_Nnewline_list_PRIME_RHS_TNEWLINE_Nnewline_list_PRIME,
	P_LHS_Nnewline_list_PRIME_RHS,
};

#define TOTAL_PROD	55

static int
shell_rhs_prod_table[TOTAL_PROD] = {
	[P_LHS_Ncomplete_command_RHS_Nlist_Nlinebreak] = 2,
	[P_LHS_Nlist_RHS_Nand_or_Nlist_PRIME] = 2,
	[P_LHS_Nlist_PRIME_RHS_Nseparator_op_Nlist_PRIME_PRIME] = 2,
	[P_LHS_Nlist_PRIME_RHS] = 0,
	[P_LHS_Nlist_PRIME_PRIME_RHS_Nand_or_Nlist_PRIME] = 2,
	[P_LHS_Nlist_PRIME_PRIME_RHS] = 0,
	[P_LHS_Nand_or_RHS_Npipeline_Nand_or_PRIME] = 2,
	[P_LHS_Nand_or_PRIME_RHS_Nand_or_op_Nlinebreak_Npipeline_Nand_or_PRIME] = 4,
	[P_LHS_Nand_or_PRIME_RHS] = 0,
	[P_LHS_Nand_or_op_RHS_TAND_IF] = 1,
	[P_LHS_Nand_or_op_RHS_TOR_IF] = 1,
	[P_LHS_Npipeline_RHS_Nbang_opt_Npipe_sequence] = 2,
	[P_LHS_Nbang_opt_RHS_TBANG] = 1,
	[P_LHS_Nbang_opt_RHS] = 0,
	[P_LHS_Npipe_sequence_RHS_Ncommand_Npipe_sequence_PRIME] = 2,
	[P_LHS_Npipe_sequence_PRIME_RHS_TPIPE_Nlinebreak_Ncommand_Npipe_sequence_PRIME] = 4,
	[P_LHS_Npipe_sequence_PRIME_RHS] = 0,
	[P_LHS_Ncommand_RHS_Ncmd_prefix_Ncommand_suffix] = 2,
	[P_LHS_Ncommand_RHS_TWORD_Ncmd_suffix_opt] = 2,
	[P_LHS_Ncommand_suffix_RHS_TWORD_Ncmd_suffix_opt] = 2,
	[P_LHS_Ncommand_suffix_RHS] = 0,
	[P_LHS_Ncmd_suffix_opt_RHS_Ncmd_suffix] = 1,
	[P_LHS_Ncmd_suffix_opt_RHS] = 0,
	[P_LHS_Ncmd_suffix_RHS_Nio_redirect_Ncmd_suffix_PRIME] = 2,
	[P_LHS_Ncmd_suffix_RHS_TWORD_Ncmd_suffix_PRIME] = 2,
	[P_LHS_Ncmd_suffix_PRIME_RHS_Nio_redirect_Ncmd_suffix_PRIME] = 2,
	[P_LHS_Ncmd_suffix_PRIME_RHS_TWORD_Ncmd_suffix_PRIME] = 2,
	[P_LHS_Ncmd_suffix_PRIME_RHS] = 0,
	[P_LHS_Ncmd_prefix_RHS_Nio_redirect_Ncmd_prefix_PRIME] = 2,
	[P_LHS_Ncmd_prefix_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME] = 2,
	[P_LHS_Ncmd_prefix_PRIME_RHS_Nio_redirect_Ncmd_prefix_PRIME] = 2,
	[P_LHS_Ncmd_prefix_PRIME_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME] = 2,
	[P_LHS_Ncmd_prefix_PRIME_RHS] = 0,
	[P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind] = 2,
	[P_LHS_Nio_number_opt_RHS_TIO_NUMBER] = 1,
	[P_LHS_Nio_number_opt_RHS] = 0,
	[P_LHS_Nio_kind_RHS_Nio_file] = 1,
	[P_LHS_Nio_kind_RHS_Nio_here] = 1,
	[P_LHS_Nio_file_RHS_TLESS_TWORD] = 2,
	[P_LHS_Nio_file_RHS_TLESSAND_TWORD] = 2,
	[P_LHS_Nio_file_RHS_TGREAT_TWORD] = 2,
	[P_LHS_Nio_file_RHS_TGREATAND_TWORD] = 2,
	[P_LHS_Nio_file_RHS_TDGEART_TWORD] = 2,
	[P_LHS_Nio_file_RHS_TLESSGREAT_TWORD] = 2,
	[P_LHS_Nio_file_RHS_TCLOBBER_TWORD] = 2,
	[P_LHS_Nio_here_RHS_TDLESS_TWORD] = 2,
	[P_LHS_Nio_here_RHS_TDLESSDASH_TWORD] = 2,
	[P_LHS_Nlinebreak_RHS_Nnewline_list] = 1,
	[P_LHS_Nlinebreak_RHS] = 0,
	[P_LHS_Nseparator_op_RHS_TAMPER] = 1,
	[P_LHS_Nseparator_op_RHS_TSEMI] = 1,
	[P_LHS_Nnewline_list_RHS_TNEWLINE_Nnewline_list_PRIME] = 2,
	[P_LHS_Nnewline_list_PRIME_RHS_TNEWLINE_Nnewline_list_PRIME] = 2,
	[P_LHS_Nnewline_list_PRIME_RHS] = 0,
};

static int
shell_lhs_prod_table[TOTAL_PROD] = {
	[P_LHS_Ncomplete_command_RHS_Nlist_Nlinebreak] = N_complete_command,
	[P_LHS_Nlist_RHS_Nand_or_Nlist_PRIME] = N_list,
	[P_LHS_Nlist_PRIME_RHS_Nseparator_op_Nlist_PRIME_PRIME] = N_list_PRIME,
	[P_LHS_Nlist_PRIME_RHS] = N_list_PRIME,
	[P_LHS_Nlist_PRIME_PRIME_RHS_Nand_or_Nlist_PRIME] = N_list_PRIME_PRIME,
	[P_LHS_Nlist_PRIME_PRIME_RHS] = N_list_PRIME_PRIME,
	[P_LHS_Nand_or_RHS_Npipeline_Nand_or_PRIME] = N_and_or,
	[P_LHS_Nand_or_PRIME_RHS_Nand_or_op_Nlinebreak_Npipeline_Nand_or_PRIME] = N_and_or_PRIME,
	[P_LHS_Nand_or_PRIME_RHS] = N_and_or_PRIME,
	[P_LHS_Nand_or_op_RHS_TAND_IF] = N_and_or_op,
	[P_LHS_Nand_or_op_RHS_TOR_IF] = N_and_or_op,
	[P_LHS_Npipeline_RHS_Nbang_opt_Npipe_sequence] = N_pipeline,
	[P_LHS_Nbang_opt_RHS_TBANG] = N_bang_opt,
	[P_LHS_Nbang_opt_RHS] = N_bang_opt,
	[P_LHS_Npipe_sequence_RHS_Ncommand_Npipe_sequence_PRIME] = N_pipe_sequence,
	[P_LHS_Npipe_sequence_PRIME_RHS_TPIPE_Nlinebreak_Ncommand_Npipe_sequence_PRIME] = N_pipe_sequence_PRIME,
	[P_LHS_Npipe_sequence_PRIME_RHS] = N_pipe_sequence_PRIME,
	[P_LHS_Ncommand_RHS_Ncmd_prefix_Ncommand_suffix] = N_command,
	[P_LHS_Ncommand_RHS_TWORD_Ncmd_suffix_opt] = N_command,
	[P_LHS_Ncommand_suffix_RHS_TWORD_Ncmd_suffix_opt] = N_command_suffix,
	[P_LHS_Ncommand_suffix_RHS] = N_command_suffix,
	[P_LHS_Ncmd_suffix_opt_RHS_Ncmd_suffix] = N_cmd_suffix_opt,
	[P_LHS_Ncmd_suffix_opt_RHS] = N_cmd_suffix_opt,
	[P_LHS_Ncmd_suffix_RHS_Nio_redirect_Ncmd_suffix_PRIME] = N_cmd_suffix,
	[P_LHS_Ncmd_suffix_RHS_TWORD_Ncmd_suffix_PRIME] = N_cmd_suffix,
	[P_LHS_Ncmd_suffix_PRIME_RHS_Nio_redirect_Ncmd_suffix_PRIME] = N_cmd_suffix_PRIME,
	[P_LHS_Ncmd_suffix_PRIME_RHS_TWORD_Ncmd_suffix_PRIME] = N_cmd_suffix_PRIME,
	[P_LHS_Ncmd_suffix_PRIME_RHS] = N_cmd_suffix_PRIME,
	[P_LHS_Ncmd_prefix_RHS_Nio_redirect_Ncmd_prefix_PRIME] = N_cmd_prefix,
	[P_LHS_Ncmd_prefix_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME] = N_cmd_prefix,
	[P_LHS_Ncmd_prefix_PRIME_RHS_Nio_redirect_Ncmd_prefix_PRIME] = N_cmd_prefix_PRIME,
	[P_LHS_Ncmd_prefix_PRIME_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME] = N_cmd_prefix_PRIME,
	[P_LHS_Ncmd_prefix_PRIME_RHS] = N_cmd_prefix_PRIME,
	[P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind] = N_io_redirect,
	[P_LHS_Nio_number_opt_RHS_TIO_NUMBER] = N_io_number_opt,
	[P_LHS_Nio_number_opt_RHS] = N_io_number_opt,
	[P_LHS_Nio_kind_RHS_Nio_file] = N_io_kind,
	[P_LHS_Nio_kind_RHS_Nio_here] = N_io_kind,
	[P_LHS_Nio_file_RHS_TLESS_TWORD] = N_io_file,
	[P_LHS_Nio_file_RHS_TLESSAND_TWORD] = N_io_file,
	[P_LHS_Nio_file_RHS_TGREAT_TWORD] = N_io_file,
	[P_LHS_Nio_file_RHS_TGREATAND_TWORD] = N_io_file,
	[P_LHS_Nio_file_RHS_TDGEART_TWORD] = N_io_file,
	[P_LHS_Nio_file_RHS_TLESSGREAT_TWORD] = N_io_file,
	[P_LHS_Nio_file_RHS_TCLOBBER_TWORD] = N_io_file,
	[P_LHS_Nio_here_RHS_TDLESS_TWORD] = N_io_here,
	[P_LHS_Nio_here_RHS_TDLESSDASH_TWORD] = N_io_here,
	[P_LHS_Nlinebreak_RHS_Nnewline_list] = N_linebreak,
	[P_LHS_Nlinebreak_RHS] = N_linebreak,
	[P_LHS_Nseparator_op_RHS_TAMPER] = N_separator_op,
	[P_LHS_Nseparator_op_RHS_TSEMI] = N_separator_op,
	[P_LHS_Nnewline_list_RHS_TNEWLINE_Nnewline_list_PRIME] = N_newline_list,
	[P_LHS_Nnewline_list_PRIME_RHS_TNEWLINE_Nnewline_list_PRIME] = N_newline_list_PRIME,
	[P_LHS_Nnewline_list_PRIME_RHS] = N_newline_list_PRIME,
};

#define ERROR_SLOT	0
#define START_SYMBOL	N_complete_command

static int
shell_ll_table[TOTAL_NTER][TOTAL_TOKEN] = {
	[N_complete_command][T_DLESSDASH]=P_LHS_Ncomplete_command_RHS_Nlist_Nlinebreak, [N_complete_command][T_DLESS]=P_LHS_Ncomplete_command_RHS_Nlist_Nlinebreak, [N_complete_command][T_CLOBBER]=P_LHS_Ncomplete_command_RHS_Nlist_Nlinebreak, [N_complete_command][T_LESSGREAT]=P_LHS_Ncomplete_command_RHS_Nlist_Nlinebreak, [N_complete_command][T_DGEART]=P_LHS_Ncomplete_command_RHS_Nlist_Nlinebreak, [N_complete_command][T_GREATAND]=P_LHS_Ncomplete_command_RHS_Nlist_Nlinebreak, [N_complete_command][T_GREAT]=P_LHS_Ncomplete_command_RHS_Nlist_Nlinebreak, [N_complete_command][T_LESSAND]=P_LHS_Ncomplete_command_RHS_Nlist_Nlinebreak, [N_complete_command][T_LESS]=P_LHS_Ncomplete_command_RHS_Nlist_Nlinebreak, [N_complete_command][T_BANG]=P_LHS_Ncomplete_command_RHS_Nlist_Nlinebreak, [N_complete_command][T_IO_NUMBER]=P_LHS_Ncomplete_command_RHS_Nlist_Nlinebreak, [N_complete_command][T_ASSIGNEMENT_WORD]=P_LHS_Ncomplete_command_RHS_Nlist_Nlinebreak, [N_complete_command][T_WORD]=P_LHS_Ncomplete_command_RHS_Nlist_Nlinebreak, 
	[N_list][T_DLESSDASH]=P_LHS_Nlist_RHS_Nand_or_Nlist_PRIME, [N_list][T_DLESS]=P_LHS_Nlist_RHS_Nand_or_Nlist_PRIME, [N_list][T_CLOBBER]=P_LHS_Nlist_RHS_Nand_or_Nlist_PRIME, [N_list][T_LESSGREAT]=P_LHS_Nlist_RHS_Nand_or_Nlist_PRIME, [N_list][T_DGEART]=P_LHS_Nlist_RHS_Nand_or_Nlist_PRIME, [N_list][T_GREATAND]=P_LHS_Nlist_RHS_Nand_or_Nlist_PRIME, [N_list][T_GREAT]=P_LHS_Nlist_RHS_Nand_or_Nlist_PRIME, [N_list][T_LESSAND]=P_LHS_Nlist_RHS_Nand_or_Nlist_PRIME, [N_list][T_LESS]=P_LHS_Nlist_RHS_Nand_or_Nlist_PRIME, [N_list][T_BANG]=P_LHS_Nlist_RHS_Nand_or_Nlist_PRIME, [N_list][T_IO_NUMBER]=P_LHS_Nlist_RHS_Nand_or_Nlist_PRIME, [N_list][T_ASSIGNEMENT_WORD]=P_LHS_Nlist_RHS_Nand_or_Nlist_PRIME, [N_list][T_WORD]=P_LHS_Nlist_RHS_Nand_or_Nlist_PRIME, 
	[N_linebreak][T_EOF]=P_LHS_Nlinebreak_RHS, [N_linebreak][T_DLESSDASH]=P_LHS_Nlinebreak_RHS, [N_linebreak][T_DLESS]=P_LHS_Nlinebreak_RHS, [N_linebreak][T_CLOBBER]=P_LHS_Nlinebreak_RHS, [N_linebreak][T_LESSGREAT]=P_LHS_Nlinebreak_RHS, [N_linebreak][T_DGEART]=P_LHS_Nlinebreak_RHS, [N_linebreak][T_GREATAND]=P_LHS_Nlinebreak_RHS, [N_linebreak][T_GREAT]=P_LHS_Nlinebreak_RHS, [N_linebreak][T_LESSAND]=P_LHS_Nlinebreak_RHS, [N_linebreak][T_LESS]=P_LHS_Nlinebreak_RHS, [N_linebreak][T_BANG]=P_LHS_Nlinebreak_RHS, [N_linebreak][T_IO_NUMBER]=P_LHS_Nlinebreak_RHS, [N_linebreak][T_ASSIGNEMENT_WORD]=P_LHS_Nlinebreak_RHS, [N_linebreak][T_WORD]=P_LHS_Nlinebreak_RHS, [N_linebreak][T_NEWLINE]=P_LHS_Nlinebreak_RHS_Nnewline_list, 
	[N_and_or][T_DLESSDASH]=P_LHS_Nand_or_RHS_Npipeline_Nand_or_PRIME, [N_and_or][T_DLESS]=P_LHS_Nand_or_RHS_Npipeline_Nand_or_PRIME, [N_and_or][T_CLOBBER]=P_LHS_Nand_or_RHS_Npipeline_Nand_or_PRIME, [N_and_or][T_LESSGREAT]=P_LHS_Nand_or_RHS_Npipeline_Nand_or_PRIME, [N_and_or][T_DGEART]=P_LHS_Nand_or_RHS_Npipeline_Nand_or_PRIME, [N_and_or][T_GREATAND]=P_LHS_Nand_or_RHS_Npipeline_Nand_or_PRIME, [N_and_or][T_GREAT]=P_LHS_Nand_or_RHS_Npipeline_Nand_or_PRIME, [N_and_or][T_LESSAND]=P_LHS_Nand_or_RHS_Npipeline_Nand_or_PRIME, [N_and_or][T_LESS]=P_LHS_Nand_or_RHS_Npipeline_Nand_or_PRIME, [N_and_or][T_BANG]=P_LHS_Nand_or_RHS_Npipeline_Nand_or_PRIME, [N_and_or][T_IO_NUMBER]=P_LHS_Nand_or_RHS_Npipeline_Nand_or_PRIME, [N_and_or][T_ASSIGNEMENT_WORD]=P_LHS_Nand_or_RHS_Npipeline_Nand_or_PRIME, [N_and_or][T_WORD]=P_LHS_Nand_or_RHS_Npipeline_Nand_or_PRIME, 
	[N_list_PRIME][T_EOF]=P_LHS_Nlist_PRIME_RHS, [N_list_PRIME][T_NEWLINE]=P_LHS_Nlist_PRIME_RHS, [N_list_PRIME][T_SEMI]=P_LHS_Nlist_PRIME_RHS_Nseparator_op_Nlist_PRIME_PRIME, [N_list_PRIME][T_AMPER]=P_LHS_Nlist_PRIME_RHS_Nseparator_op_Nlist_PRIME_PRIME, 
	[N_separator_op][T_SEMI]=P_LHS_Nseparator_op_RHS_TSEMI, [N_separator_op][T_AMPER]=P_LHS_Nseparator_op_RHS_TAMPER, 
	[N_list_PRIME_PRIME][T_EOF]=P_LHS_Nlist_PRIME_PRIME_RHS, [N_list_PRIME_PRIME][T_NEWLINE]=P_LHS_Nlist_PRIME_PRIME_RHS, [N_list_PRIME_PRIME][T_DLESSDASH]=P_LHS_Nlist_PRIME_PRIME_RHS_Nand_or_Nlist_PRIME, [N_list_PRIME_PRIME][T_DLESS]=P_LHS_Nlist_PRIME_PRIME_RHS_Nand_or_Nlist_PRIME, [N_list_PRIME_PRIME][T_CLOBBER]=P_LHS_Nlist_PRIME_PRIME_RHS_Nand_or_Nlist_PRIME, [N_list_PRIME_PRIME][T_LESSGREAT]=P_LHS_Nlist_PRIME_PRIME_RHS_Nand_or_Nlist_PRIME, [N_list_PRIME_PRIME][T_DGEART]=P_LHS_Nlist_PRIME_PRIME_RHS_Nand_or_Nlist_PRIME, [N_list_PRIME_PRIME][T_GREATAND]=P_LHS_Nlist_PRIME_PRIME_RHS_Nand_or_Nlist_PRIME, [N_list_PRIME_PRIME][T_GREAT]=P_LHS_Nlist_PRIME_PRIME_RHS_Nand_or_Nlist_PRIME, [N_list_PRIME_PRIME][T_LESSAND]=P_LHS_Nlist_PRIME_PRIME_RHS_Nand_or_Nlist_PRIME, [N_list_PRIME_PRIME][T_LESS]=P_LHS_Nlist_PRIME_PRIME_RHS_Nand_or_Nlist_PRIME, [N_list_PRIME_PRIME][T_BANG]=P_LHS_Nlist_PRIME_PRIME_RHS_Nand_or_Nlist_PRIME, [N_list_PRIME_PRIME][T_IO_NUMBER]=P_LHS_Nlist_PRIME_PRIME_RHS_Nand_or_Nlist_PRIME, [N_list_PRIME_PRIME][T_ASSIGNEMENT_WORD]=P_LHS_Nlist_PRIME_PRIME_RHS_Nand_or_Nlist_PRIME, [N_list_PRIME_PRIME][T_WORD]=P_LHS_Nlist_PRIME_PRIME_RHS_Nand_or_Nlist_PRIME, 
	[N_pipeline][T_DLESSDASH]=P_LHS_Npipeline_RHS_Nbang_opt_Npipe_sequence, [N_pipeline][T_DLESS]=P_LHS_Npipeline_RHS_Nbang_opt_Npipe_sequence, [N_pipeline][T_CLOBBER]=P_LHS_Npipeline_RHS_Nbang_opt_Npipe_sequence, [N_pipeline][T_LESSGREAT]=P_LHS_Npipeline_RHS_Nbang_opt_Npipe_sequence, [N_pipeline][T_DGEART]=P_LHS_Npipeline_RHS_Nbang_opt_Npipe_sequence, [N_pipeline][T_GREATAND]=P_LHS_Npipeline_RHS_Nbang_opt_Npipe_sequence, [N_pipeline][T_GREAT]=P_LHS_Npipeline_RHS_Nbang_opt_Npipe_sequence, [N_pipeline][T_LESSAND]=P_LHS_Npipeline_RHS_Nbang_opt_Npipe_sequence, [N_pipeline][T_LESS]=P_LHS_Npipeline_RHS_Nbang_opt_Npipe_sequence, [N_pipeline][T_BANG]=P_LHS_Npipeline_RHS_Nbang_opt_Npipe_sequence, [N_pipeline][T_IO_NUMBER]=P_LHS_Npipeline_RHS_Nbang_opt_Npipe_sequence, [N_pipeline][T_ASSIGNEMENT_WORD]=P_LHS_Npipeline_RHS_Nbang_opt_Npipe_sequence, [N_pipeline][T_WORD]=P_LHS_Npipeline_RHS_Nbang_opt_Npipe_sequence, 
	[N_and_or_PRIME][T_EOF]=P_LHS_Nand_or_PRIME_RHS, [N_and_or_PRIME][T_SEMI]=P_LHS_Nand_or_PRIME_RHS, [N_and_or_PRIME][T_AMPER]=P_LHS_Nand_or_PRIME_RHS, [N_and_or_PRIME][T_NEWLINE]=P_LHS_Nand_or_PRIME_RHS, [N_and_or_PRIME][T_OR_IF]=P_LHS_Nand_or_PRIME_RHS_Nand_or_op_Nlinebreak_Npipeline_Nand_or_PRIME, [N_and_or_PRIME][T_AND_IF]=P_LHS_Nand_or_PRIME_RHS_Nand_or_op_Nlinebreak_Npipeline_Nand_or_PRIME, 
	[N_and_or_op][T_OR_IF]=P_LHS_Nand_or_op_RHS_TOR_IF, [N_and_or_op][T_AND_IF]=P_LHS_Nand_or_op_RHS_TAND_IF, 
	[N_bang_opt][T_DLESSDASH]=P_LHS_Nbang_opt_RHS, [N_bang_opt][T_DLESS]=P_LHS_Nbang_opt_RHS, [N_bang_opt][T_CLOBBER]=P_LHS_Nbang_opt_RHS, [N_bang_opt][T_LESSGREAT]=P_LHS_Nbang_opt_RHS, [N_bang_opt][T_DGEART]=P_LHS_Nbang_opt_RHS, [N_bang_opt][T_GREATAND]=P_LHS_Nbang_opt_RHS, [N_bang_opt][T_GREAT]=P_LHS_Nbang_opt_RHS, [N_bang_opt][T_LESSAND]=P_LHS_Nbang_opt_RHS, [N_bang_opt][T_LESS]=P_LHS_Nbang_opt_RHS, [N_bang_opt][T_IO_NUMBER]=P_LHS_Nbang_opt_RHS, [N_bang_opt][T_ASSIGNEMENT_WORD]=P_LHS_Nbang_opt_RHS, [N_bang_opt][T_WORD]=P_LHS_Nbang_opt_RHS, [N_bang_opt][T_BANG]=P_LHS_Nbang_opt_RHS_TBANG, 
	[N_pipe_sequence][T_DLESSDASH]=P_LHS_Npipe_sequence_RHS_Ncommand_Npipe_sequence_PRIME, [N_pipe_sequence][T_DLESS]=P_LHS_Npipe_sequence_RHS_Ncommand_Npipe_sequence_PRIME, [N_pipe_sequence][T_CLOBBER]=P_LHS_Npipe_sequence_RHS_Ncommand_Npipe_sequence_PRIME, [N_pipe_sequence][T_LESSGREAT]=P_LHS_Npipe_sequence_RHS_Ncommand_Npipe_sequence_PRIME, [N_pipe_sequence][T_DGEART]=P_LHS_Npipe_sequence_RHS_Ncommand_Npipe_sequence_PRIME, [N_pipe_sequence][T_GREATAND]=P_LHS_Npipe_sequence_RHS_Ncommand_Npipe_sequence_PRIME, [N_pipe_sequence][T_GREAT]=P_LHS_Npipe_sequence_RHS_Ncommand_Npipe_sequence_PRIME, [N_pipe_sequence][T_LESSAND]=P_LHS_Npipe_sequence_RHS_Ncommand_Npipe_sequence_PRIME, [N_pipe_sequence][T_LESS]=P_LHS_Npipe_sequence_RHS_Ncommand_Npipe_sequence_PRIME, [N_pipe_sequence][T_IO_NUMBER]=P_LHS_Npipe_sequence_RHS_Ncommand_Npipe_sequence_PRIME, [N_pipe_sequence][T_ASSIGNEMENT_WORD]=P_LHS_Npipe_sequence_RHS_Ncommand_Npipe_sequence_PRIME, [N_pipe_sequence][T_WORD]=P_LHS_Npipe_sequence_RHS_Ncommand_Npipe_sequence_PRIME, 
	[N_command][T_WORD]=P_LHS_Ncommand_RHS_TWORD_Ncmd_suffix_opt, [N_command][T_DLESSDASH]=P_LHS_Ncommand_RHS_Ncmd_prefix_Ncommand_suffix, [N_command][T_DLESS]=P_LHS_Ncommand_RHS_Ncmd_prefix_Ncommand_suffix, [N_command][T_CLOBBER]=P_LHS_Ncommand_RHS_Ncmd_prefix_Ncommand_suffix, [N_command][T_LESSGREAT]=P_LHS_Ncommand_RHS_Ncmd_prefix_Ncommand_suffix, [N_command][T_DGEART]=P_LHS_Ncommand_RHS_Ncmd_prefix_Ncommand_suffix, [N_command][T_GREATAND]=P_LHS_Ncommand_RHS_Ncmd_prefix_Ncommand_suffix, [N_command][T_GREAT]=P_LHS_Ncommand_RHS_Ncmd_prefix_Ncommand_suffix, [N_command][T_LESSAND]=P_LHS_Ncommand_RHS_Ncmd_prefix_Ncommand_suffix, [N_command][T_LESS]=P_LHS_Ncommand_RHS_Ncmd_prefix_Ncommand_suffix, [N_command][T_IO_NUMBER]=P_LHS_Ncommand_RHS_Ncmd_prefix_Ncommand_suffix, [N_command][T_ASSIGNEMENT_WORD]=P_LHS_Ncommand_RHS_Ncmd_prefix_Ncommand_suffix, 
	[N_pipe_sequence_PRIME][T_EOF]=P_LHS_Npipe_sequence_PRIME_RHS, [N_pipe_sequence_PRIME][T_OR_IF]=P_LHS_Npipe_sequence_PRIME_RHS, [N_pipe_sequence_PRIME][T_AND_IF]=P_LHS_Npipe_sequence_PRIME_RHS, [N_pipe_sequence_PRIME][T_SEMI]=P_LHS_Npipe_sequence_PRIME_RHS, [N_pipe_sequence_PRIME][T_AMPER]=P_LHS_Npipe_sequence_PRIME_RHS, [N_pipe_sequence_PRIME][T_NEWLINE]=P_LHS_Npipe_sequence_PRIME_RHS, [N_pipe_sequence_PRIME][T_PIPE]=P_LHS_Npipe_sequence_PRIME_RHS_TPIPE_Nlinebreak_Ncommand_Npipe_sequence_PRIME, 
	[N_cmd_prefix][T_ASSIGNEMENT_WORD]=P_LHS_Ncmd_prefix_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME, [N_cmd_prefix][T_DLESSDASH]=P_LHS_Ncmd_prefix_RHS_Nio_redirect_Ncmd_prefix_PRIME, [N_cmd_prefix][T_DLESS]=P_LHS_Ncmd_prefix_RHS_Nio_redirect_Ncmd_prefix_PRIME, [N_cmd_prefix][T_CLOBBER]=P_LHS_Ncmd_prefix_RHS_Nio_redirect_Ncmd_prefix_PRIME, [N_cmd_prefix][T_LESSGREAT]=P_LHS_Ncmd_prefix_RHS_Nio_redirect_Ncmd_prefix_PRIME, [N_cmd_prefix][T_DGEART]=P_LHS_Ncmd_prefix_RHS_Nio_redirect_Ncmd_prefix_PRIME, [N_cmd_prefix][T_GREATAND]=P_LHS_Ncmd_prefix_RHS_Nio_redirect_Ncmd_prefix_PRIME, [N_cmd_prefix][T_GREAT]=P_LHS_Ncmd_prefix_RHS_Nio_redirect_Ncmd_prefix_PRIME, [N_cmd_prefix][T_LESSAND]=P_LHS_Ncmd_prefix_RHS_Nio_redirect_Ncmd_prefix_PRIME, [N_cmd_prefix][T_LESS]=P_LHS_Ncmd_prefix_RHS_Nio_redirect_Ncmd_prefix_PRIME, [N_cmd_prefix][T_IO_NUMBER]=P_LHS_Ncmd_prefix_RHS_Nio_redirect_Ncmd_prefix_PRIME, 
	[N_command_suffix][T_EOF]=P_LHS_Ncommand_suffix_RHS, [N_command_suffix][T_PIPE]=P_LHS_Ncommand_suffix_RHS, [N_command_suffix][T_OR_IF]=P_LHS_Ncommand_suffix_RHS, [N_command_suffix][T_AND_IF]=P_LHS_Ncommand_suffix_RHS, [N_command_suffix][T_SEMI]=P_LHS_Ncommand_suffix_RHS, [N_command_suffix][T_AMPER]=P_LHS_Ncommand_suffix_RHS, [N_command_suffix][T_NEWLINE]=P_LHS_Ncommand_suffix_RHS, [N_command_suffix][T_WORD]=P_LHS_Ncommand_suffix_RHS_TWORD_Ncmd_suffix_opt, 
	[N_cmd_suffix_opt][T_EOF]=P_LHS_Ncmd_suffix_opt_RHS, [N_cmd_suffix_opt][T_PIPE]=P_LHS_Ncmd_suffix_opt_RHS, [N_cmd_suffix_opt][T_OR_IF]=P_LHS_Ncmd_suffix_opt_RHS, [N_cmd_suffix_opt][T_AND_IF]=P_LHS_Ncmd_suffix_opt_RHS, [N_cmd_suffix_opt][T_SEMI]=P_LHS_Ncmd_suffix_opt_RHS, [N_cmd_suffix_opt][T_AMPER]=P_LHS_Ncmd_suffix_opt_RHS, [N_cmd_suffix_opt][T_NEWLINE]=P_LHS_Ncmd_suffix_opt_RHS, [N_cmd_suffix_opt][T_DLESSDASH]=P_LHS_Ncmd_suffix_opt_RHS_Ncmd_suffix, [N_cmd_suffix_opt][T_DLESS]=P_LHS_Ncmd_suffix_opt_RHS_Ncmd_suffix, [N_cmd_suffix_opt][T_CLOBBER]=P_LHS_Ncmd_suffix_opt_RHS_Ncmd_suffix, [N_cmd_suffix_opt][T_LESSGREAT]=P_LHS_Ncmd_suffix_opt_RHS_Ncmd_suffix, [N_cmd_suffix_opt][T_DGEART]=P_LHS_Ncmd_suffix_opt_RHS_Ncmd_suffix, [N_cmd_suffix_opt][T_GREATAND]=P_LHS_Ncmd_suffix_opt_RHS_Ncmd_suffix, [N_cmd_suffix_opt][T_GREAT]=P_LHS_Ncmd_suffix_opt_RHS_Ncmd_suffix, [N_cmd_suffix_opt][T_LESSAND]=P_LHS_Ncmd_suffix_opt_RHS_Ncmd_suffix, [N_cmd_suffix_opt][T_LESS]=P_LHS_Ncmd_suffix_opt_RHS_Ncmd_suffix, [N_cmd_suffix_opt][T_IO_NUMBER]=P_LHS_Ncmd_suffix_opt_RHS_Ncmd_suffix, [N_cmd_suffix_opt][T_WORD]=P_LHS_Ncmd_suffix_opt_RHS_Ncmd_suffix, 
	[N_cmd_suffix][T_WORD]=P_LHS_Ncmd_suffix_RHS_TWORD_Ncmd_suffix_PRIME, [N_cmd_suffix][T_DLESSDASH]=P_LHS_Ncmd_suffix_RHS_Nio_redirect_Ncmd_suffix_PRIME, [N_cmd_suffix][T_DLESS]=P_LHS_Ncmd_suffix_RHS_Nio_redirect_Ncmd_suffix_PRIME, [N_cmd_suffix][T_CLOBBER]=P_LHS_Ncmd_suffix_RHS_Nio_redirect_Ncmd_suffix_PRIME, [N_cmd_suffix][T_LESSGREAT]=P_LHS_Ncmd_suffix_RHS_Nio_redirect_Ncmd_suffix_PRIME, [N_cmd_suffix][T_DGEART]=P_LHS_Ncmd_suffix_RHS_Nio_redirect_Ncmd_suffix_PRIME, [N_cmd_suffix][T_GREATAND]=P_LHS_Ncmd_suffix_RHS_Nio_redirect_Ncmd_suffix_PRIME, [N_cmd_suffix][T_GREAT]=P_LHS_Ncmd_suffix_RHS_Nio_redirect_Ncmd_suffix_PRIME, [N_cmd_suffix][T_LESSAND]=P_LHS_Ncmd_suffix_RHS_Nio_redirect_Ncmd_suffix_PRIME, [N_cmd_suffix][T_LESS]=P_LHS_Ncmd_suffix_RHS_Nio_redirect_Ncmd_suffix_PRIME, [N_cmd_suffix][T_IO_NUMBER]=P_LHS_Ncmd_suffix_RHS_Nio_redirect_Ncmd_suffix_PRIME, 
	[N_io_redirect][T_DLESSDASH]=P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind, [N_io_redirect][T_DLESS]=P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind, [N_io_redirect][T_CLOBBER]=P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind, [N_io_redirect][T_LESSGREAT]=P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind, [N_io_redirect][T_DGEART]=P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind, [N_io_redirect][T_GREATAND]=P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind, [N_io_redirect][T_GREAT]=P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind, [N_io_redirect][T_LESSAND]=P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind, [N_io_redirect][T_LESS]=P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind, [N_io_redirect][T_IO_NUMBER]=P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind, 
	[N_cmd_suffix_PRIME][T_EOF]=P_LHS_Ncmd_suffix_PRIME_RHS, [N_cmd_suffix_PRIME][T_PIPE]=P_LHS_Ncmd_suffix_PRIME_RHS, [N_cmd_suffix_PRIME][T_OR_IF]=P_LHS_Ncmd_suffix_PRIME_RHS, [N_cmd_suffix_PRIME][T_AND_IF]=P_LHS_Ncmd_suffix_PRIME_RHS, [N_cmd_suffix_PRIME][T_SEMI]=P_LHS_Ncmd_suffix_PRIME_RHS, [N_cmd_suffix_PRIME][T_AMPER]=P_LHS_Ncmd_suffix_PRIME_RHS, [N_cmd_suffix_PRIME][T_NEWLINE]=P_LHS_Ncmd_suffix_PRIME_RHS, [N_cmd_suffix_PRIME][T_WORD]=P_LHS_Ncmd_suffix_PRIME_RHS_TWORD_Ncmd_suffix_PRIME, [N_cmd_suffix_PRIME][T_DLESSDASH]=P_LHS_Ncmd_suffix_PRIME_RHS_Nio_redirect_Ncmd_suffix_PRIME, [N_cmd_suffix_PRIME][T_DLESS]=P_LHS_Ncmd_suffix_PRIME_RHS_Nio_redirect_Ncmd_suffix_PRIME, [N_cmd_suffix_PRIME][T_CLOBBER]=P_LHS_Ncmd_suffix_PRIME_RHS_Nio_redirect_Ncmd_suffix_PRIME, [N_cmd_suffix_PRIME][T_LESSGREAT]=P_LHS_Ncmd_suffix_PRIME_RHS_Nio_redirect_Ncmd_suffix_PRIME, [N_cmd_suffix_PRIME][T_DGEART]=P_LHS_Ncmd_suffix_PRIME_RHS_Nio_redirect_Ncmd_suffix_PRIME, [N_cmd_suffix_PRIME][T_GREATAND]=P_LHS_Ncmd_suffix_PRIME_RHS_Nio_redirect_Ncmd_suffix_PRIME, [N_cmd_suffix_PRIME][T_GREAT]=P_LHS_Ncmd_suffix_PRIME_RHS_Nio_redirect_Ncmd_suffix_PRIME, [N_cmd_suffix_PRIME][T_LESSAND]=P_LHS_Ncmd_suffix_PRIME_RHS_Nio_redirect_Ncmd_suffix_PRIME, [N_cmd_suffix_PRIME][T_LESS]=P_LHS_Ncmd_suffix_PRIME_RHS_Nio_redirect_Ncmd_suffix_PRIME, [N_cmd_suffix_PRIME][T_IO_NUMBER]=P_LHS_Ncmd_suffix_PRIME_RHS_Nio_redirect_Ncmd_suffix_PRIME, 
	[N_cmd_prefix_PRIME][T_EOF]=P_LHS_Ncmd_prefix_PRIME_RHS, [N_cmd_prefix_PRIME][T_PIPE]=P_LHS_Ncmd_prefix_PRIME_RHS, [N_cmd_prefix_PRIME][T_OR_IF]=P_LHS_Ncmd_prefix_PRIME_RHS, [N_cmd_prefix_PRIME][T_AND_IF]=P_LHS_Ncmd_prefix_PRIME_RHS, [N_cmd_prefix_PRIME][T_SEMI]=P_LHS_Ncmd_prefix_PRIME_RHS, [N_cmd_prefix_PRIME][T_AMPER]=P_LHS_Ncmd_prefix_PRIME_RHS, [N_cmd_prefix_PRIME][T_NEWLINE]=P_LHS_Ncmd_prefix_PRIME_RHS, [N_cmd_prefix_PRIME][T_WORD]=P_LHS_Ncmd_prefix_PRIME_RHS, [N_cmd_prefix_PRIME][T_ASSIGNEMENT_WORD]=P_LHS_Ncmd_prefix_PRIME_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME, [N_cmd_prefix_PRIME][T_DLESSDASH]=P_LHS_Ncmd_prefix_PRIME_RHS_Nio_redirect_Ncmd_prefix_PRIME, [N_cmd_prefix_PRIME][T_DLESS]=P_LHS_Ncmd_prefix_PRIME_RHS_Nio_redirect_Ncmd_prefix_PRIME, [N_cmd_prefix_PRIME][T_CLOBBER]=P_LHS_Ncmd_prefix_PRIME_RHS_Nio_redirect_Ncmd_prefix_PRIME, [N_cmd_prefix_PRIME][T_LESSGREAT]=P_LHS_Ncmd_prefix_PRIME_RHS_Nio_redirect_Ncmd_prefix_PRIME, [N_cmd_prefix_PRIME][T_DGEART]=P_LHS_Ncmd_prefix_PRIME_RHS_Nio_redirect_Ncmd_prefix_PRIME, [N_cmd_prefix_PRIME][T_GREATAND]=P_LHS_Ncmd_prefix_PRIME_RHS_Nio_redirect_Ncmd_prefix_PRIME, [N_cmd_prefix_PRIME][T_GREAT]=P_LHS_Ncmd_prefix_PRIME_RHS_Nio_redirect_Ncmd_prefix_PRIME, [N_cmd_prefix_PRIME][T_LESSAND]=P_LHS_Ncmd_prefix_PRIME_RHS_Nio_redirect_Ncmd_prefix_PRIME, [N_cmd_prefix_PRIME][T_LESS]=P_LHS_Ncmd_prefix_PRIME_RHS_Nio_redirect_Ncmd_prefix_PRIME, [N_cmd_prefix_PRIME][T_IO_NUMBER]=P_LHS_Ncmd_prefix_PRIME_RHS_Nio_redirect_Ncmd_prefix_PRIME, 
	[N_io_number_opt][T_DLESSDASH]=P_LHS_Nio_number_opt_RHS, [N_io_number_opt][T_DLESS]=P_LHS_Nio_number_opt_RHS, [N_io_number_opt][T_CLOBBER]=P_LHS_Nio_number_opt_RHS, [N_io_number_opt][T_LESSGREAT]=P_LHS_Nio_number_opt_RHS, [N_io_number_opt][T_DGEART]=P_LHS_Nio_number_opt_RHS, [N_io_number_opt][T_GREATAND]=P_LHS_Nio_number_opt_RHS, [N_io_number_opt][T_GREAT]=P_LHS_Nio_number_opt_RHS, [N_io_number_opt][T_LESSAND]=P_LHS_Nio_number_opt_RHS, [N_io_number_opt][T_LESS]=P_LHS_Nio_number_opt_RHS, [N_io_number_opt][T_IO_NUMBER]=P_LHS_Nio_number_opt_RHS_TIO_NUMBER, 
	[N_io_kind][T_DLESSDASH]=P_LHS_Nio_kind_RHS_Nio_here, [N_io_kind][T_DLESS]=P_LHS_Nio_kind_RHS_Nio_here, [N_io_kind][T_CLOBBER]=P_LHS_Nio_kind_RHS_Nio_file, [N_io_kind][T_LESSGREAT]=P_LHS_Nio_kind_RHS_Nio_file, [N_io_kind][T_DGEART]=P_LHS_Nio_kind_RHS_Nio_file, [N_io_kind][T_GREATAND]=P_LHS_Nio_kind_RHS_Nio_file, [N_io_kind][T_GREAT]=P_LHS_Nio_kind_RHS_Nio_file, [N_io_kind][T_LESSAND]=P_LHS_Nio_kind_RHS_Nio_file, [N_io_kind][T_LESS]=P_LHS_Nio_kind_RHS_Nio_file, 
	[N_io_file][T_CLOBBER]=P_LHS_Nio_file_RHS_TCLOBBER_TWORD, [N_io_file][T_LESSGREAT]=P_LHS_Nio_file_RHS_TLESSGREAT_TWORD, [N_io_file][T_DGEART]=P_LHS_Nio_file_RHS_TDGEART_TWORD, [N_io_file][T_GREATAND]=P_LHS_Nio_file_RHS_TGREATAND_TWORD, [N_io_file][T_GREAT]=P_LHS_Nio_file_RHS_TGREAT_TWORD, [N_io_file][T_LESSAND]=P_LHS_Nio_file_RHS_TLESSAND_TWORD, [N_io_file][T_LESS]=P_LHS_Nio_file_RHS_TLESS_TWORD, 
	[N_io_here][T_DLESSDASH]=P_LHS_Nio_here_RHS_TDLESSDASH_TWORD, [N_io_here][T_DLESS]=P_LHS_Nio_here_RHS_TDLESS_TWORD, 
	[N_newline_list][T_NEWLINE]=P_LHS_Nnewline_list_RHS_TNEWLINE_Nnewline_list_PRIME, 
	[N_newline_list_PRIME][T_EOF]=P_LHS_Nnewline_list_PRIME_RHS, [N_newline_list_PRIME][T_DLESSDASH]=P_LHS_Nnewline_list_PRIME_RHS, [N_newline_list_PRIME][T_DLESS]=P_LHS_Nnewline_list_PRIME_RHS, [N_newline_list_PRIME][T_CLOBBER]=P_LHS_Nnewline_list_PRIME_RHS, [N_newline_list_PRIME][T_LESSGREAT]=P_LHS_Nnewline_list_PRIME_RHS, [N_newline_list_PRIME][T_DGEART]=P_LHS_Nnewline_list_PRIME_RHS, [N_newline_list_PRIME][T_GREATAND]=P_LHS_Nnewline_list_PRIME_RHS, [N_newline_list_PRIME][T_GREAT]=P_LHS_Nnewline_list_PRIME_RHS, [N_newline_list_PRIME][T_LESSAND]=P_LHS_Nnewline_list_PRIME_RHS, [N_newline_list_PRIME][T_LESS]=P_LHS_Nnewline_list_PRIME_RHS, [N_newline_list_PRIME][T_BANG]=P_LHS_Nnewline_list_PRIME_RHS, [N_newline_list_PRIME][T_IO_NUMBER]=P_LHS_Nnewline_list_PRIME_RHS, [N_newline_list_PRIME][T_ASSIGNEMENT_WORD]=P_LHS_Nnewline_list_PRIME_RHS, [N_newline_list_PRIME][T_WORD]=P_LHS_Nnewline_list_PRIME_RHS, [N_newline_list_PRIME][T_NEWLINE]=P_LHS_Nnewline_list_PRIME_RHS_TNEWLINE_Nnewline_list_PRIME, 
};

#if 0

enum {
	_SHIFT	= 0x1000,
	_REDUCE	= 0x2000,
	_GOTO	= 0x4000,
};

#define SHIFT(x)	(x | _SHIFT)
#define REDUCE(x)	(x | _REDUCE)
#define GOTO(x)	(x | _GOTO)
#define ACCEPT	(~0)

#define LR_START_STATE	0

static int
shell_lr_action_table[80][TOTAL_TOKEN] = {
/*   0 */	{[T_BANG]=SHIFT(6), [T_DLESSDASH]=REDUCE(P_LHS_Nbang_opt_RHS), [T_DLESS]=REDUCE(P_LHS_Nbang_opt_RHS), [T_CLOBBER]=REDUCE(P_LHS_Nbang_opt_RHS), [T_LESSGREAT]=REDUCE(P_LHS_Nbang_opt_RHS), [T_DGEART]=REDUCE(P_LHS_Nbang_opt_RHS), [T_GREATAND]=REDUCE(P_LHS_Nbang_opt_RHS), [T_GREAT]=REDUCE(P_LHS_Nbang_opt_RHS), [T_LESSAND]=REDUCE(P_LHS_Nbang_opt_RHS), [T_LESS]=REDUCE(P_LHS_Nbang_opt_RHS), [T_IO_NUMBER]=REDUCE(P_LHS_Nbang_opt_RHS), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nbang_opt_RHS), [T_WORD]=REDUCE(P_LHS_Nbang_opt_RHS)},
/*   1 */	{[T_EOF]=ACCEPT,},
/*   2 */	{[T_NEWLINE]=SHIFT(59), [T_EOF]=REDUCE(P_LHS_Nlinebreak_RHS)},
/*   3 */	{[T_SEMI]=SHIFT(75), [T_AMPER]=SHIFT(74), [T_EOF]=REDUCE(P_LHS_Nlist_PRIME_RHS), [T_NEWLINE]=REDUCE(P_LHS_Nlist_PRIME_RHS)},
/*   4 */	{[T_OR_IF]=SHIFT(68), [T_AND_IF]=SHIFT(67), [T_EOF]=REDUCE(P_LHS_Nand_or_PRIME_RHS), [T_SEMI]=REDUCE(P_LHS_Nand_or_PRIME_RHS), [T_AMPER]=REDUCE(P_LHS_Nand_or_PRIME_RHS), [T_NEWLINE]=REDUCE(P_LHS_Nand_or_PRIME_RHS)},
/*   5 */	{[T_IO_NUMBER]=SHIFT(14), [T_ASSIGNEMENT_WORD]=SHIFT(12), [T_WORD]=SHIFT(10), [T_DLESSDASH]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DLESS]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_CLOBBER]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSGREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DGEART]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREATAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESS]=REDUCE(P_LHS_Nio_number_opt_RHS)},
/*   6 */	{[T_DLESSDASH]=REDUCE(P_LHS_Nbang_opt_RHS_TBANG), [T_DLESS]=REDUCE(P_LHS_Nbang_opt_RHS_TBANG), [T_CLOBBER]=REDUCE(P_LHS_Nbang_opt_RHS_TBANG), [T_LESSGREAT]=REDUCE(P_LHS_Nbang_opt_RHS_TBANG), [T_DGEART]=REDUCE(P_LHS_Nbang_opt_RHS_TBANG), [T_GREATAND]=REDUCE(P_LHS_Nbang_opt_RHS_TBANG), [T_GREAT]=REDUCE(P_LHS_Nbang_opt_RHS_TBANG), [T_LESSAND]=REDUCE(P_LHS_Nbang_opt_RHS_TBANG), [T_LESS]=REDUCE(P_LHS_Nbang_opt_RHS_TBANG), [T_IO_NUMBER]=REDUCE(P_LHS_Nbang_opt_RHS_TBANG), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nbang_opt_RHS_TBANG), [T_WORD]=REDUCE(P_LHS_Nbang_opt_RHS_TBANG)},
/*   7 */	{[T_EOF]=REDUCE(P_LHS_Npipeline_RHS_Nbang_opt_Npipe_sequence), [T_OR_IF]=REDUCE(P_LHS_Npipeline_RHS_Nbang_opt_Npipe_sequence), [T_AND_IF]=REDUCE(P_LHS_Npipeline_RHS_Nbang_opt_Npipe_sequence), [T_SEMI]=REDUCE(P_LHS_Npipeline_RHS_Nbang_opt_Npipe_sequence), [T_AMPER]=REDUCE(P_LHS_Npipeline_RHS_Nbang_opt_Npipe_sequence), [T_NEWLINE]=REDUCE(P_LHS_Npipeline_RHS_Nbang_opt_Npipe_sequence)},
/*   8 */	{[T_PIPE]=SHIFT(56), [T_EOF]=REDUCE(P_LHS_Npipe_sequence_PRIME_RHS), [T_OR_IF]=REDUCE(P_LHS_Npipe_sequence_PRIME_RHS), [T_AND_IF]=REDUCE(P_LHS_Npipe_sequence_PRIME_RHS), [T_SEMI]=REDUCE(P_LHS_Npipe_sequence_PRIME_RHS), [T_AMPER]=REDUCE(P_LHS_Npipe_sequence_PRIME_RHS), [T_NEWLINE]=REDUCE(P_LHS_Npipe_sequence_PRIME_RHS)},
/*   9 */	{[T_WORD]=SHIFT(53), [T_EOF]=REDUCE(P_LHS_Ncommand_suffix_RHS), [T_PIPE]=REDUCE(P_LHS_Ncommand_suffix_RHS), [T_OR_IF]=REDUCE(P_LHS_Ncommand_suffix_RHS), [T_AND_IF]=REDUCE(P_LHS_Ncommand_suffix_RHS), [T_SEMI]=REDUCE(P_LHS_Ncommand_suffix_RHS), [T_AMPER]=REDUCE(P_LHS_Ncommand_suffix_RHS), [T_NEWLINE]=REDUCE(P_LHS_Ncommand_suffix_RHS)},
/*  10 */	{[T_WORD]=SHIFT(45), [T_IO_NUMBER]=SHIFT(14), [T_DLESSDASH]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DLESS]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_CLOBBER]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSGREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DGEART]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREATAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESS]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_EOF]=REDUCE(P_LHS_Ncmd_suffix_opt_RHS), [T_PIPE]=REDUCE(P_LHS_Ncmd_suffix_opt_RHS), [T_OR_IF]=REDUCE(P_LHS_Ncmd_suffix_opt_RHS), [T_AND_IF]=REDUCE(P_LHS_Ncmd_suffix_opt_RHS), [T_SEMI]=REDUCE(P_LHS_Ncmd_suffix_opt_RHS), [T_AMPER]=REDUCE(P_LHS_Ncmd_suffix_opt_RHS), [T_NEWLINE]=REDUCE(P_LHS_Ncmd_suffix_opt_RHS)},
/*  11 */	{[T_ASSIGNEMENT_WORD]=SHIFT(37), [T_IO_NUMBER]=SHIFT(14), [T_DLESSDASH]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DLESS]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_CLOBBER]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSGREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DGEART]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREATAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESS]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_EOF]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_PIPE]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_OR_IF]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_AND_IF]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_SEMI]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_AMPER]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_NEWLINE]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_WORD]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS)},
/*  12 */	{[T_ASSIGNEMENT_WORD]=SHIFT(37), [T_IO_NUMBER]=SHIFT(14), [T_DLESSDASH]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DLESS]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_CLOBBER]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSGREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DGEART]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREATAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESS]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_EOF]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_PIPE]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_OR_IF]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_AND_IF]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_SEMI]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_AMPER]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_NEWLINE]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_WORD]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS)},
/*  13 */	{[T_DLESSDASH]=SHIFT(26), [T_DLESS]=SHIFT(25), [T_CLOBBER]=SHIFT(24), [T_LESSGREAT]=SHIFT(23), [T_DGEART]=SHIFT(22), [T_GREATAND]=SHIFT(21), [T_GREAT]=SHIFT(20), [T_LESSAND]=SHIFT(19), [T_LESS]=SHIFT(18)},
/*  14 */	{[T_DLESSDASH]=REDUCE(P_LHS_Nio_number_opt_RHS_TIO_NUMBER), [T_DLESS]=REDUCE(P_LHS_Nio_number_opt_RHS_TIO_NUMBER), [T_CLOBBER]=REDUCE(P_LHS_Nio_number_opt_RHS_TIO_NUMBER), [T_LESSGREAT]=REDUCE(P_LHS_Nio_number_opt_RHS_TIO_NUMBER), [T_DGEART]=REDUCE(P_LHS_Nio_number_opt_RHS_TIO_NUMBER), [T_GREATAND]=REDUCE(P_LHS_Nio_number_opt_RHS_TIO_NUMBER), [T_GREAT]=REDUCE(P_LHS_Nio_number_opt_RHS_TIO_NUMBER), [T_LESSAND]=REDUCE(P_LHS_Nio_number_opt_RHS_TIO_NUMBER), [T_LESS]=REDUCE(P_LHS_Nio_number_opt_RHS_TIO_NUMBER)},
/*  15 */	{[T_EOF]=REDUCE(P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind), [T_DLESSDASH]=REDUCE(P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind), [T_DLESS]=REDUCE(P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind), [T_CLOBBER]=REDUCE(P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind), [T_LESSGREAT]=REDUCE(P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind), [T_DGEART]=REDUCE(P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind), [T_GREATAND]=REDUCE(P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind), [T_GREAT]=REDUCE(P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind), [T_LESSAND]=REDUCE(P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind), [T_LESS]=REDUCE(P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind), [T_PIPE]=REDUCE(P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind), [T_OR_IF]=REDUCE(P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind), [T_AND_IF]=REDUCE(P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind), [T_SEMI]=REDUCE(P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind), [T_AMPER]=REDUCE(P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind), [T_NEWLINE]=REDUCE(P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind), [T_IO_NUMBER]=REDUCE(P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind), [T_WORD]=REDUCE(P_LHS_Nio_redirect_RHS_Nio_number_opt_Nio_kind)},
/*  16 */	{[T_EOF]=REDUCE(P_LHS_Nio_kind_RHS_Nio_file), [T_DLESSDASH]=REDUCE(P_LHS_Nio_kind_RHS_Nio_file), [T_DLESS]=REDUCE(P_LHS_Nio_kind_RHS_Nio_file), [T_CLOBBER]=REDUCE(P_LHS_Nio_kind_RHS_Nio_file), [T_LESSGREAT]=REDUCE(P_LHS_Nio_kind_RHS_Nio_file), [T_DGEART]=REDUCE(P_LHS_Nio_kind_RHS_Nio_file), [T_GREATAND]=REDUCE(P_LHS_Nio_kind_RHS_Nio_file), [T_GREAT]=REDUCE(P_LHS_Nio_kind_RHS_Nio_file), [T_LESSAND]=REDUCE(P_LHS_Nio_kind_RHS_Nio_file), [T_LESS]=REDUCE(P_LHS_Nio_kind_RHS_Nio_file), [T_PIPE]=REDUCE(P_LHS_Nio_kind_RHS_Nio_file), [T_OR_IF]=REDUCE(P_LHS_Nio_kind_RHS_Nio_file), [T_AND_IF]=REDUCE(P_LHS_Nio_kind_RHS_Nio_file), [T_SEMI]=REDUCE(P_LHS_Nio_kind_RHS_Nio_file), [T_AMPER]=REDUCE(P_LHS_Nio_kind_RHS_Nio_file), [T_NEWLINE]=REDUCE(P_LHS_Nio_kind_RHS_Nio_file), [T_IO_NUMBER]=REDUCE(P_LHS_Nio_kind_RHS_Nio_file), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nio_kind_RHS_Nio_file), [T_WORD]=REDUCE(P_LHS_Nio_kind_RHS_Nio_file)},
/*  17 */	{[T_EOF]=REDUCE(P_LHS_Nio_kind_RHS_Nio_here), [T_DLESSDASH]=REDUCE(P_LHS_Nio_kind_RHS_Nio_here), [T_DLESS]=REDUCE(P_LHS_Nio_kind_RHS_Nio_here), [T_CLOBBER]=REDUCE(P_LHS_Nio_kind_RHS_Nio_here), [T_LESSGREAT]=REDUCE(P_LHS_Nio_kind_RHS_Nio_here), [T_DGEART]=REDUCE(P_LHS_Nio_kind_RHS_Nio_here), [T_GREATAND]=REDUCE(P_LHS_Nio_kind_RHS_Nio_here), [T_GREAT]=REDUCE(P_LHS_Nio_kind_RHS_Nio_here), [T_LESSAND]=REDUCE(P_LHS_Nio_kind_RHS_Nio_here), [T_LESS]=REDUCE(P_LHS_Nio_kind_RHS_Nio_here), [T_PIPE]=REDUCE(P_LHS_Nio_kind_RHS_Nio_here), [T_OR_IF]=REDUCE(P_LHS_Nio_kind_RHS_Nio_here), [T_AND_IF]=REDUCE(P_LHS_Nio_kind_RHS_Nio_here), [T_SEMI]=REDUCE(P_LHS_Nio_kind_RHS_Nio_here), [T_AMPER]=REDUCE(P_LHS_Nio_kind_RHS_Nio_here), [T_NEWLINE]=REDUCE(P_LHS_Nio_kind_RHS_Nio_here), [T_IO_NUMBER]=REDUCE(P_LHS_Nio_kind_RHS_Nio_here), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nio_kind_RHS_Nio_here), [T_WORD]=REDUCE(P_LHS_Nio_kind_RHS_Nio_here)},
/*  18 */	{[T_WORD]=SHIFT(35)},
/*  19 */	{[T_WORD]=SHIFT(34)},
/*  20 */	{[T_WORD]=SHIFT(33)},
/*  21 */	{[T_WORD]=SHIFT(32)},
/*  22 */	{[T_WORD]=SHIFT(31)},
/*  23 */	{[T_WORD]=SHIFT(30)},
/*  24 */	{[T_WORD]=SHIFT(29)},
/*  25 */	{[T_WORD]=SHIFT(28)},
/*  26 */	{[T_WORD]=SHIFT(27)},
/*  27 */	{[T_EOF]=REDUCE(P_LHS_Nio_here_RHS_TDLESSDASH_TWORD), [T_DLESSDASH]=REDUCE(P_LHS_Nio_here_RHS_TDLESSDASH_TWORD), [T_DLESS]=REDUCE(P_LHS_Nio_here_RHS_TDLESSDASH_TWORD), [T_CLOBBER]=REDUCE(P_LHS_Nio_here_RHS_TDLESSDASH_TWORD), [T_LESSGREAT]=REDUCE(P_LHS_Nio_here_RHS_TDLESSDASH_TWORD), [T_DGEART]=REDUCE(P_LHS_Nio_here_RHS_TDLESSDASH_TWORD), [T_GREATAND]=REDUCE(P_LHS_Nio_here_RHS_TDLESSDASH_TWORD), [T_GREAT]=REDUCE(P_LHS_Nio_here_RHS_TDLESSDASH_TWORD), [T_LESSAND]=REDUCE(P_LHS_Nio_here_RHS_TDLESSDASH_TWORD), [T_LESS]=REDUCE(P_LHS_Nio_here_RHS_TDLESSDASH_TWORD), [T_PIPE]=REDUCE(P_LHS_Nio_here_RHS_TDLESSDASH_TWORD), [T_OR_IF]=REDUCE(P_LHS_Nio_here_RHS_TDLESSDASH_TWORD), [T_AND_IF]=REDUCE(P_LHS_Nio_here_RHS_TDLESSDASH_TWORD), [T_SEMI]=REDUCE(P_LHS_Nio_here_RHS_TDLESSDASH_TWORD), [T_AMPER]=REDUCE(P_LHS_Nio_here_RHS_TDLESSDASH_TWORD), [T_NEWLINE]=REDUCE(P_LHS_Nio_here_RHS_TDLESSDASH_TWORD), [T_IO_NUMBER]=REDUCE(P_LHS_Nio_here_RHS_TDLESSDASH_TWORD), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nio_here_RHS_TDLESSDASH_TWORD), [T_WORD]=REDUCE(P_LHS_Nio_here_RHS_TDLESSDASH_TWORD)},
/*  28 */	{[T_EOF]=REDUCE(P_LHS_Nio_here_RHS_TDLESS_TWORD), [T_DLESSDASH]=REDUCE(P_LHS_Nio_here_RHS_TDLESS_TWORD), [T_DLESS]=REDUCE(P_LHS_Nio_here_RHS_TDLESS_TWORD), [T_CLOBBER]=REDUCE(P_LHS_Nio_here_RHS_TDLESS_TWORD), [T_LESSGREAT]=REDUCE(P_LHS_Nio_here_RHS_TDLESS_TWORD), [T_DGEART]=REDUCE(P_LHS_Nio_here_RHS_TDLESS_TWORD), [T_GREATAND]=REDUCE(P_LHS_Nio_here_RHS_TDLESS_TWORD), [T_GREAT]=REDUCE(P_LHS_Nio_here_RHS_TDLESS_TWORD), [T_LESSAND]=REDUCE(P_LHS_Nio_here_RHS_TDLESS_TWORD), [T_LESS]=REDUCE(P_LHS_Nio_here_RHS_TDLESS_TWORD), [T_PIPE]=REDUCE(P_LHS_Nio_here_RHS_TDLESS_TWORD), [T_OR_IF]=REDUCE(P_LHS_Nio_here_RHS_TDLESS_TWORD), [T_AND_IF]=REDUCE(P_LHS_Nio_here_RHS_TDLESS_TWORD), [T_SEMI]=REDUCE(P_LHS_Nio_here_RHS_TDLESS_TWORD), [T_AMPER]=REDUCE(P_LHS_Nio_here_RHS_TDLESS_TWORD), [T_NEWLINE]=REDUCE(P_LHS_Nio_here_RHS_TDLESS_TWORD), [T_IO_NUMBER]=REDUCE(P_LHS_Nio_here_RHS_TDLESS_TWORD), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nio_here_RHS_TDLESS_TWORD), [T_WORD]=REDUCE(P_LHS_Nio_here_RHS_TDLESS_TWORD)},
/*  29 */	{[T_EOF]=REDUCE(P_LHS_Nio_file_RHS_TCLOBBER_TWORD), [T_DLESSDASH]=REDUCE(P_LHS_Nio_file_RHS_TCLOBBER_TWORD), [T_DLESS]=REDUCE(P_LHS_Nio_file_RHS_TCLOBBER_TWORD), [T_CLOBBER]=REDUCE(P_LHS_Nio_file_RHS_TCLOBBER_TWORD), [T_LESSGREAT]=REDUCE(P_LHS_Nio_file_RHS_TCLOBBER_TWORD), [T_DGEART]=REDUCE(P_LHS_Nio_file_RHS_TCLOBBER_TWORD), [T_GREATAND]=REDUCE(P_LHS_Nio_file_RHS_TCLOBBER_TWORD), [T_GREAT]=REDUCE(P_LHS_Nio_file_RHS_TCLOBBER_TWORD), [T_LESSAND]=REDUCE(P_LHS_Nio_file_RHS_TCLOBBER_TWORD), [T_LESS]=REDUCE(P_LHS_Nio_file_RHS_TCLOBBER_TWORD), [T_PIPE]=REDUCE(P_LHS_Nio_file_RHS_TCLOBBER_TWORD), [T_OR_IF]=REDUCE(P_LHS_Nio_file_RHS_TCLOBBER_TWORD), [T_AND_IF]=REDUCE(P_LHS_Nio_file_RHS_TCLOBBER_TWORD), [T_SEMI]=REDUCE(P_LHS_Nio_file_RHS_TCLOBBER_TWORD), [T_AMPER]=REDUCE(P_LHS_Nio_file_RHS_TCLOBBER_TWORD), [T_NEWLINE]=REDUCE(P_LHS_Nio_file_RHS_TCLOBBER_TWORD), [T_IO_NUMBER]=REDUCE(P_LHS_Nio_file_RHS_TCLOBBER_TWORD), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nio_file_RHS_TCLOBBER_TWORD), [T_WORD]=REDUCE(P_LHS_Nio_file_RHS_TCLOBBER_TWORD)},
/*  30 */	{[T_EOF]=REDUCE(P_LHS_Nio_file_RHS_TLESSGREAT_TWORD), [T_DLESSDASH]=REDUCE(P_LHS_Nio_file_RHS_TLESSGREAT_TWORD), [T_DLESS]=REDUCE(P_LHS_Nio_file_RHS_TLESSGREAT_TWORD), [T_CLOBBER]=REDUCE(P_LHS_Nio_file_RHS_TLESSGREAT_TWORD), [T_LESSGREAT]=REDUCE(P_LHS_Nio_file_RHS_TLESSGREAT_TWORD), [T_DGEART]=REDUCE(P_LHS_Nio_file_RHS_TLESSGREAT_TWORD), [T_GREATAND]=REDUCE(P_LHS_Nio_file_RHS_TLESSGREAT_TWORD), [T_GREAT]=REDUCE(P_LHS_Nio_file_RHS_TLESSGREAT_TWORD), [T_LESSAND]=REDUCE(P_LHS_Nio_file_RHS_TLESSGREAT_TWORD), [T_LESS]=REDUCE(P_LHS_Nio_file_RHS_TLESSGREAT_TWORD), [T_PIPE]=REDUCE(P_LHS_Nio_file_RHS_TLESSGREAT_TWORD), [T_OR_IF]=REDUCE(P_LHS_Nio_file_RHS_TLESSGREAT_TWORD), [T_AND_IF]=REDUCE(P_LHS_Nio_file_RHS_TLESSGREAT_TWORD), [T_SEMI]=REDUCE(P_LHS_Nio_file_RHS_TLESSGREAT_TWORD), [T_AMPER]=REDUCE(P_LHS_Nio_file_RHS_TLESSGREAT_TWORD), [T_NEWLINE]=REDUCE(P_LHS_Nio_file_RHS_TLESSGREAT_TWORD), [T_IO_NUMBER]=REDUCE(P_LHS_Nio_file_RHS_TLESSGREAT_TWORD), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nio_file_RHS_TLESSGREAT_TWORD), [T_WORD]=REDUCE(P_LHS_Nio_file_RHS_TLESSGREAT_TWORD)},
/*  31 */	{[T_EOF]=REDUCE(P_LHS_Nio_file_RHS_TDGEART_TWORD), [T_DLESSDASH]=REDUCE(P_LHS_Nio_file_RHS_TDGEART_TWORD), [T_DLESS]=REDUCE(P_LHS_Nio_file_RHS_TDGEART_TWORD), [T_CLOBBER]=REDUCE(P_LHS_Nio_file_RHS_TDGEART_TWORD), [T_LESSGREAT]=REDUCE(P_LHS_Nio_file_RHS_TDGEART_TWORD), [T_DGEART]=REDUCE(P_LHS_Nio_file_RHS_TDGEART_TWORD), [T_GREATAND]=REDUCE(P_LHS_Nio_file_RHS_TDGEART_TWORD), [T_GREAT]=REDUCE(P_LHS_Nio_file_RHS_TDGEART_TWORD), [T_LESSAND]=REDUCE(P_LHS_Nio_file_RHS_TDGEART_TWORD), [T_LESS]=REDUCE(P_LHS_Nio_file_RHS_TDGEART_TWORD), [T_PIPE]=REDUCE(P_LHS_Nio_file_RHS_TDGEART_TWORD), [T_OR_IF]=REDUCE(P_LHS_Nio_file_RHS_TDGEART_TWORD), [T_AND_IF]=REDUCE(P_LHS_Nio_file_RHS_TDGEART_TWORD), [T_SEMI]=REDUCE(P_LHS_Nio_file_RHS_TDGEART_TWORD), [T_AMPER]=REDUCE(P_LHS_Nio_file_RHS_TDGEART_TWORD), [T_NEWLINE]=REDUCE(P_LHS_Nio_file_RHS_TDGEART_TWORD), [T_IO_NUMBER]=REDUCE(P_LHS_Nio_file_RHS_TDGEART_TWORD), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nio_file_RHS_TDGEART_TWORD), [T_WORD]=REDUCE(P_LHS_Nio_file_RHS_TDGEART_TWORD)},
/*  32 */	{[T_EOF]=REDUCE(P_LHS_Nio_file_RHS_TGREATAND_TWORD), [T_DLESSDASH]=REDUCE(P_LHS_Nio_file_RHS_TGREATAND_TWORD), [T_DLESS]=REDUCE(P_LHS_Nio_file_RHS_TGREATAND_TWORD), [T_CLOBBER]=REDUCE(P_LHS_Nio_file_RHS_TGREATAND_TWORD), [T_LESSGREAT]=REDUCE(P_LHS_Nio_file_RHS_TGREATAND_TWORD), [T_DGEART]=REDUCE(P_LHS_Nio_file_RHS_TGREATAND_TWORD), [T_GREATAND]=REDUCE(P_LHS_Nio_file_RHS_TGREATAND_TWORD), [T_GREAT]=REDUCE(P_LHS_Nio_file_RHS_TGREATAND_TWORD), [T_LESSAND]=REDUCE(P_LHS_Nio_file_RHS_TGREATAND_TWORD), [T_LESS]=REDUCE(P_LHS_Nio_file_RHS_TGREATAND_TWORD), [T_PIPE]=REDUCE(P_LHS_Nio_file_RHS_TGREATAND_TWORD), [T_OR_IF]=REDUCE(P_LHS_Nio_file_RHS_TGREATAND_TWORD), [T_AND_IF]=REDUCE(P_LHS_Nio_file_RHS_TGREATAND_TWORD), [T_SEMI]=REDUCE(P_LHS_Nio_file_RHS_TGREATAND_TWORD), [T_AMPER]=REDUCE(P_LHS_Nio_file_RHS_TGREATAND_TWORD), [T_NEWLINE]=REDUCE(P_LHS_Nio_file_RHS_TGREATAND_TWORD), [T_IO_NUMBER]=REDUCE(P_LHS_Nio_file_RHS_TGREATAND_TWORD), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nio_file_RHS_TGREATAND_TWORD), [T_WORD]=REDUCE(P_LHS_Nio_file_RHS_TGREATAND_TWORD)},
/*  33 */	{[T_EOF]=REDUCE(P_LHS_Nio_file_RHS_TGREAT_TWORD), [T_DLESSDASH]=REDUCE(P_LHS_Nio_file_RHS_TGREAT_TWORD), [T_DLESS]=REDUCE(P_LHS_Nio_file_RHS_TGREAT_TWORD), [T_CLOBBER]=REDUCE(P_LHS_Nio_file_RHS_TGREAT_TWORD), [T_LESSGREAT]=REDUCE(P_LHS_Nio_file_RHS_TGREAT_TWORD), [T_DGEART]=REDUCE(P_LHS_Nio_file_RHS_TGREAT_TWORD), [T_GREATAND]=REDUCE(P_LHS_Nio_file_RHS_TGREAT_TWORD), [T_GREAT]=REDUCE(P_LHS_Nio_file_RHS_TGREAT_TWORD), [T_LESSAND]=REDUCE(P_LHS_Nio_file_RHS_TGREAT_TWORD), [T_LESS]=REDUCE(P_LHS_Nio_file_RHS_TGREAT_TWORD), [T_PIPE]=REDUCE(P_LHS_Nio_file_RHS_TGREAT_TWORD), [T_OR_IF]=REDUCE(P_LHS_Nio_file_RHS_TGREAT_TWORD), [T_AND_IF]=REDUCE(P_LHS_Nio_file_RHS_TGREAT_TWORD), [T_SEMI]=REDUCE(P_LHS_Nio_file_RHS_TGREAT_TWORD), [T_AMPER]=REDUCE(P_LHS_Nio_file_RHS_TGREAT_TWORD), [T_NEWLINE]=REDUCE(P_LHS_Nio_file_RHS_TGREAT_TWORD), [T_IO_NUMBER]=REDUCE(P_LHS_Nio_file_RHS_TGREAT_TWORD), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nio_file_RHS_TGREAT_TWORD), [T_WORD]=REDUCE(P_LHS_Nio_file_RHS_TGREAT_TWORD)},
/*  34 */	{[T_EOF]=REDUCE(P_LHS_Nio_file_RHS_TLESSAND_TWORD), [T_DLESSDASH]=REDUCE(P_LHS_Nio_file_RHS_TLESSAND_TWORD), [T_DLESS]=REDUCE(P_LHS_Nio_file_RHS_TLESSAND_TWORD), [T_CLOBBER]=REDUCE(P_LHS_Nio_file_RHS_TLESSAND_TWORD), [T_LESSGREAT]=REDUCE(P_LHS_Nio_file_RHS_TLESSAND_TWORD), [T_DGEART]=REDUCE(P_LHS_Nio_file_RHS_TLESSAND_TWORD), [T_GREATAND]=REDUCE(P_LHS_Nio_file_RHS_TLESSAND_TWORD), [T_GREAT]=REDUCE(P_LHS_Nio_file_RHS_TLESSAND_TWORD), [T_LESSAND]=REDUCE(P_LHS_Nio_file_RHS_TLESSAND_TWORD), [T_LESS]=REDUCE(P_LHS_Nio_file_RHS_TLESSAND_TWORD), [T_PIPE]=REDUCE(P_LHS_Nio_file_RHS_TLESSAND_TWORD), [T_OR_IF]=REDUCE(P_LHS_Nio_file_RHS_TLESSAND_TWORD), [T_AND_IF]=REDUCE(P_LHS_Nio_file_RHS_TLESSAND_TWORD), [T_SEMI]=REDUCE(P_LHS_Nio_file_RHS_TLESSAND_TWORD), [T_AMPER]=REDUCE(P_LHS_Nio_file_RHS_TLESSAND_TWORD), [T_NEWLINE]=REDUCE(P_LHS_Nio_file_RHS_TLESSAND_TWORD), [T_IO_NUMBER]=REDUCE(P_LHS_Nio_file_RHS_TLESSAND_TWORD), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nio_file_RHS_TLESSAND_TWORD), [T_WORD]=REDUCE(P_LHS_Nio_file_RHS_TLESSAND_TWORD)},
/*  35 */	{[T_EOF]=REDUCE(P_LHS_Nio_file_RHS_TLESS_TWORD), [T_DLESSDASH]=REDUCE(P_LHS_Nio_file_RHS_TLESS_TWORD), [T_DLESS]=REDUCE(P_LHS_Nio_file_RHS_TLESS_TWORD), [T_CLOBBER]=REDUCE(P_LHS_Nio_file_RHS_TLESS_TWORD), [T_LESSGREAT]=REDUCE(P_LHS_Nio_file_RHS_TLESS_TWORD), [T_DGEART]=REDUCE(P_LHS_Nio_file_RHS_TLESS_TWORD), [T_GREATAND]=REDUCE(P_LHS_Nio_file_RHS_TLESS_TWORD), [T_GREAT]=REDUCE(P_LHS_Nio_file_RHS_TLESS_TWORD), [T_LESSAND]=REDUCE(P_LHS_Nio_file_RHS_TLESS_TWORD), [T_LESS]=REDUCE(P_LHS_Nio_file_RHS_TLESS_TWORD), [T_PIPE]=REDUCE(P_LHS_Nio_file_RHS_TLESS_TWORD), [T_OR_IF]=REDUCE(P_LHS_Nio_file_RHS_TLESS_TWORD), [T_AND_IF]=REDUCE(P_LHS_Nio_file_RHS_TLESS_TWORD), [T_SEMI]=REDUCE(P_LHS_Nio_file_RHS_TLESS_TWORD), [T_AMPER]=REDUCE(P_LHS_Nio_file_RHS_TLESS_TWORD), [T_NEWLINE]=REDUCE(P_LHS_Nio_file_RHS_TLESS_TWORD), [T_IO_NUMBER]=REDUCE(P_LHS_Nio_file_RHS_TLESS_TWORD), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nio_file_RHS_TLESS_TWORD), [T_WORD]=REDUCE(P_LHS_Nio_file_RHS_TLESS_TWORD)},
/*  36 */	{[T_ASSIGNEMENT_WORD]=SHIFT(37), [T_IO_NUMBER]=SHIFT(14), [T_DLESSDASH]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DLESS]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_CLOBBER]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSGREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DGEART]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREATAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESS]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_EOF]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_PIPE]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_OR_IF]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_AND_IF]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_SEMI]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_AMPER]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_NEWLINE]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_WORD]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS)},
/*  37 */	{[T_ASSIGNEMENT_WORD]=SHIFT(37), [T_IO_NUMBER]=SHIFT(14), [T_DLESSDASH]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DLESS]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_CLOBBER]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSGREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DGEART]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREATAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESS]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_EOF]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_PIPE]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_OR_IF]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_AND_IF]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_SEMI]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_AMPER]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_NEWLINE]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS), [T_WORD]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS)},
/*  38 */	{[T_EOF]=REDUCE(P_LHS_Ncmd_prefix_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME), [T_PIPE]=REDUCE(P_LHS_Ncmd_prefix_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME), [T_OR_IF]=REDUCE(P_LHS_Ncmd_prefix_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME), [T_AND_IF]=REDUCE(P_LHS_Ncmd_prefix_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME), [T_SEMI]=REDUCE(P_LHS_Ncmd_prefix_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME), [T_AMPER]=REDUCE(P_LHS_Ncmd_prefix_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME), [T_NEWLINE]=REDUCE(P_LHS_Ncmd_prefix_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME), [T_WORD]=REDUCE(P_LHS_Ncmd_prefix_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME)},
/*  39 */	{[T_EOF]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME), [T_PIPE]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME), [T_OR_IF]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME), [T_AND_IF]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME), [T_SEMI]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME), [T_AMPER]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME), [T_NEWLINE]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME), [T_WORD]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS_TASSIGNEMENT_WORD_Ncmd_prefix_PRIME)},
/*  40 */	{[T_EOF]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS_Nio_redirect_Ncmd_prefix_PRIME), [T_PIPE]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS_Nio_redirect_Ncmd_prefix_PRIME), [T_OR_IF]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS_Nio_redirect_Ncmd_prefix_PRIME), [T_AND_IF]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS_Nio_redirect_Ncmd_prefix_PRIME), [T_SEMI]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS_Nio_redirect_Ncmd_prefix_PRIME), [T_AMPER]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS_Nio_redirect_Ncmd_prefix_PRIME), [T_NEWLINE]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS_Nio_redirect_Ncmd_prefix_PRIME), [T_WORD]=REDUCE(P_LHS_Ncmd_prefix_PRIME_RHS_Nio_redirect_Ncmd_prefix_PRIME)},
/*  41 */	{[T_EOF]=REDUCE(P_LHS_Ncmd_prefix_RHS_Nio_redirect_Ncmd_prefix_PRIME), [T_PIPE]=REDUCE(P_LHS_Ncmd_prefix_RHS_Nio_redirect_Ncmd_prefix_PRIME), [T_OR_IF]=REDUCE(P_LHS_Ncmd_prefix_RHS_Nio_redirect_Ncmd_prefix_PRIME), [T_AND_IF]=REDUCE(P_LHS_Ncmd_prefix_RHS_Nio_redirect_Ncmd_prefix_PRIME), [T_SEMI]=REDUCE(P_LHS_Ncmd_prefix_RHS_Nio_redirect_Ncmd_prefix_PRIME), [T_AMPER]=REDUCE(P_LHS_Ncmd_prefix_RHS_Nio_redirect_Ncmd_prefix_PRIME), [T_NEWLINE]=REDUCE(P_LHS_Ncmd_prefix_RHS_Nio_redirect_Ncmd_prefix_PRIME), [T_WORD]=REDUCE(P_LHS_Ncmd_prefix_RHS_Nio_redirect_Ncmd_prefix_PRIME)},
/*  42 */	{[T_EOF]=REDUCE(P_LHS_Ncommand_RHS_TWORD_Ncmd_suffix_opt), [T_PIPE]=REDUCE(P_LHS_Ncommand_RHS_TWORD_Ncmd_suffix_opt), [T_OR_IF]=REDUCE(P_LHS_Ncommand_RHS_TWORD_Ncmd_suffix_opt), [T_AND_IF]=REDUCE(P_LHS_Ncommand_RHS_TWORD_Ncmd_suffix_opt), [T_SEMI]=REDUCE(P_LHS_Ncommand_RHS_TWORD_Ncmd_suffix_opt), [T_AMPER]=REDUCE(P_LHS_Ncommand_RHS_TWORD_Ncmd_suffix_opt), [T_NEWLINE]=REDUCE(P_LHS_Ncommand_RHS_TWORD_Ncmd_suffix_opt)},
/*  43 */	{[T_EOF]=REDUCE(P_LHS_Ncmd_suffix_opt_RHS_Ncmd_suffix), [T_PIPE]=REDUCE(P_LHS_Ncmd_suffix_opt_RHS_Ncmd_suffix), [T_OR_IF]=REDUCE(P_LHS_Ncmd_suffix_opt_RHS_Ncmd_suffix), [T_AND_IF]=REDUCE(P_LHS_Ncmd_suffix_opt_RHS_Ncmd_suffix), [T_SEMI]=REDUCE(P_LHS_Ncmd_suffix_opt_RHS_Ncmd_suffix), [T_AMPER]=REDUCE(P_LHS_Ncmd_suffix_opt_RHS_Ncmd_suffix), [T_NEWLINE]=REDUCE(P_LHS_Ncmd_suffix_opt_RHS_Ncmd_suffix)},
/*  44 */	{[T_WORD]=SHIFT(47), [T_IO_NUMBER]=SHIFT(14), [T_DLESSDASH]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DLESS]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_CLOBBER]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSGREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DGEART]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREATAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESS]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_EOF]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_PIPE]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_OR_IF]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_AND_IF]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_SEMI]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_AMPER]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_NEWLINE]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS)},
/*  45 */	{[T_WORD]=SHIFT(47), [T_IO_NUMBER]=SHIFT(14), [T_DLESSDASH]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DLESS]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_CLOBBER]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSGREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DGEART]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREATAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESS]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_EOF]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_PIPE]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_OR_IF]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_AND_IF]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_SEMI]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_AMPER]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_NEWLINE]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS)},
/*  46 */	{[T_WORD]=SHIFT(47), [T_IO_NUMBER]=SHIFT(14), [T_DLESSDASH]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DLESS]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_CLOBBER]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSGREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DGEART]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREATAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESS]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_EOF]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_PIPE]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_OR_IF]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_AND_IF]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_SEMI]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_AMPER]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_NEWLINE]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS)},
/*  47 */	{[T_WORD]=SHIFT(47), [T_IO_NUMBER]=SHIFT(14), [T_DLESSDASH]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DLESS]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_CLOBBER]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSGREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DGEART]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREATAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESS]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_EOF]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_PIPE]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_OR_IF]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_AND_IF]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_SEMI]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_AMPER]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS), [T_NEWLINE]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS)},
/*  48 */	{[T_EOF]=REDUCE(P_LHS_Ncmd_suffix_RHS_TWORD_Ncmd_suffix_PRIME), [T_PIPE]=REDUCE(P_LHS_Ncmd_suffix_RHS_TWORD_Ncmd_suffix_PRIME), [T_OR_IF]=REDUCE(P_LHS_Ncmd_suffix_RHS_TWORD_Ncmd_suffix_PRIME), [T_AND_IF]=REDUCE(P_LHS_Ncmd_suffix_RHS_TWORD_Ncmd_suffix_PRIME), [T_SEMI]=REDUCE(P_LHS_Ncmd_suffix_RHS_TWORD_Ncmd_suffix_PRIME), [T_AMPER]=REDUCE(P_LHS_Ncmd_suffix_RHS_TWORD_Ncmd_suffix_PRIME), [T_NEWLINE]=REDUCE(P_LHS_Ncmd_suffix_RHS_TWORD_Ncmd_suffix_PRIME)},
/*  49 */	{[T_EOF]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS_TWORD_Ncmd_suffix_PRIME), [T_PIPE]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS_TWORD_Ncmd_suffix_PRIME), [T_OR_IF]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS_TWORD_Ncmd_suffix_PRIME), [T_AND_IF]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS_TWORD_Ncmd_suffix_PRIME), [T_SEMI]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS_TWORD_Ncmd_suffix_PRIME), [T_AMPER]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS_TWORD_Ncmd_suffix_PRIME), [T_NEWLINE]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS_TWORD_Ncmd_suffix_PRIME)},
/*  50 */	{[T_EOF]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS_Nio_redirect_Ncmd_suffix_PRIME), [T_PIPE]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS_Nio_redirect_Ncmd_suffix_PRIME), [T_OR_IF]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS_Nio_redirect_Ncmd_suffix_PRIME), [T_AND_IF]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS_Nio_redirect_Ncmd_suffix_PRIME), [T_SEMI]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS_Nio_redirect_Ncmd_suffix_PRIME), [T_AMPER]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS_Nio_redirect_Ncmd_suffix_PRIME), [T_NEWLINE]=REDUCE(P_LHS_Ncmd_suffix_PRIME_RHS_Nio_redirect_Ncmd_suffix_PRIME)},
/*  51 */	{[T_EOF]=REDUCE(P_LHS_Ncmd_suffix_RHS_Nio_redirect_Ncmd_suffix_PRIME), [T_PIPE]=REDUCE(P_LHS_Ncmd_suffix_RHS_Nio_redirect_Ncmd_suffix_PRIME), [T_OR_IF]=REDUCE(P_LHS_Ncmd_suffix_RHS_Nio_redirect_Ncmd_suffix_PRIME), [T_AND_IF]=REDUCE(P_LHS_Ncmd_suffix_RHS_Nio_redirect_Ncmd_suffix_PRIME), [T_SEMI]=REDUCE(P_LHS_Ncmd_suffix_RHS_Nio_redirect_Ncmd_suffix_PRIME), [T_AMPER]=REDUCE(P_LHS_Ncmd_suffix_RHS_Nio_redirect_Ncmd_suffix_PRIME), [T_NEWLINE]=REDUCE(P_LHS_Ncmd_suffix_RHS_Nio_redirect_Ncmd_suffix_PRIME)},
/*  52 */	{[T_EOF]=REDUCE(P_LHS_Ncommand_RHS_Ncmd_prefix_Ncommand_suffix), [T_PIPE]=REDUCE(P_LHS_Ncommand_RHS_Ncmd_prefix_Ncommand_suffix), [T_OR_IF]=REDUCE(P_LHS_Ncommand_RHS_Ncmd_prefix_Ncommand_suffix), [T_AND_IF]=REDUCE(P_LHS_Ncommand_RHS_Ncmd_prefix_Ncommand_suffix), [T_SEMI]=REDUCE(P_LHS_Ncommand_RHS_Ncmd_prefix_Ncommand_suffix), [T_AMPER]=REDUCE(P_LHS_Ncommand_RHS_Ncmd_prefix_Ncommand_suffix), [T_NEWLINE]=REDUCE(P_LHS_Ncommand_RHS_Ncmd_prefix_Ncommand_suffix)},
/*  53 */	{[T_WORD]=SHIFT(45), [T_IO_NUMBER]=SHIFT(14), [T_DLESSDASH]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DLESS]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_CLOBBER]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSGREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DGEART]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREATAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESS]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_EOF]=REDUCE(P_LHS_Ncmd_suffix_opt_RHS), [T_PIPE]=REDUCE(P_LHS_Ncmd_suffix_opt_RHS), [T_OR_IF]=REDUCE(P_LHS_Ncmd_suffix_opt_RHS), [T_AND_IF]=REDUCE(P_LHS_Ncmd_suffix_opt_RHS), [T_SEMI]=REDUCE(P_LHS_Ncmd_suffix_opt_RHS), [T_AMPER]=REDUCE(P_LHS_Ncmd_suffix_opt_RHS), [T_NEWLINE]=REDUCE(P_LHS_Ncmd_suffix_opt_RHS)},
/*  54 */	{[T_EOF]=REDUCE(P_LHS_Ncommand_suffix_RHS_TWORD_Ncmd_suffix_opt), [T_PIPE]=REDUCE(P_LHS_Ncommand_suffix_RHS_TWORD_Ncmd_suffix_opt), [T_OR_IF]=REDUCE(P_LHS_Ncommand_suffix_RHS_TWORD_Ncmd_suffix_opt), [T_AND_IF]=REDUCE(P_LHS_Ncommand_suffix_RHS_TWORD_Ncmd_suffix_opt), [T_SEMI]=REDUCE(P_LHS_Ncommand_suffix_RHS_TWORD_Ncmd_suffix_opt), [T_AMPER]=REDUCE(P_LHS_Ncommand_suffix_RHS_TWORD_Ncmd_suffix_opt), [T_NEWLINE]=REDUCE(P_LHS_Ncommand_suffix_RHS_TWORD_Ncmd_suffix_opt)},
/*  55 */	{[T_EOF]=REDUCE(P_LHS_Npipe_sequence_RHS_Ncommand_Npipe_sequence_PRIME), [T_OR_IF]=REDUCE(P_LHS_Npipe_sequence_RHS_Ncommand_Npipe_sequence_PRIME), [T_AND_IF]=REDUCE(P_LHS_Npipe_sequence_RHS_Ncommand_Npipe_sequence_PRIME), [T_SEMI]=REDUCE(P_LHS_Npipe_sequence_RHS_Ncommand_Npipe_sequence_PRIME), [T_AMPER]=REDUCE(P_LHS_Npipe_sequence_RHS_Ncommand_Npipe_sequence_PRIME), [T_NEWLINE]=REDUCE(P_LHS_Npipe_sequence_RHS_Ncommand_Npipe_sequence_PRIME)},
/*  56 */	{[T_NEWLINE]=SHIFT(59), [T_DLESSDASH]=REDUCE(P_LHS_Nlinebreak_RHS), [T_DLESS]=REDUCE(P_LHS_Nlinebreak_RHS), [T_CLOBBER]=REDUCE(P_LHS_Nlinebreak_RHS), [T_LESSGREAT]=REDUCE(P_LHS_Nlinebreak_RHS), [T_DGEART]=REDUCE(P_LHS_Nlinebreak_RHS), [T_GREATAND]=REDUCE(P_LHS_Nlinebreak_RHS), [T_GREAT]=REDUCE(P_LHS_Nlinebreak_RHS), [T_LESSAND]=REDUCE(P_LHS_Nlinebreak_RHS), [T_LESS]=REDUCE(P_LHS_Nlinebreak_RHS), [T_IO_NUMBER]=REDUCE(P_LHS_Nlinebreak_RHS), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nlinebreak_RHS), [T_WORD]=REDUCE(P_LHS_Nlinebreak_RHS)},
/*  57 */	{[T_IO_NUMBER]=SHIFT(14), [T_ASSIGNEMENT_WORD]=SHIFT(12), [T_WORD]=SHIFT(10), [T_DLESSDASH]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DLESS]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_CLOBBER]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSGREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_DGEART]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREATAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_GREAT]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESSAND]=REDUCE(P_LHS_Nio_number_opt_RHS), [T_LESS]=REDUCE(P_LHS_Nio_number_opt_RHS)},
/*  58 */	{[T_EOF]=REDUCE(P_LHS_Nlinebreak_RHS_Nnewline_list), [T_DLESSDASH]=REDUCE(P_LHS_Nlinebreak_RHS_Nnewline_list), [T_DLESS]=REDUCE(P_LHS_Nlinebreak_RHS_Nnewline_list), [T_CLOBBER]=REDUCE(P_LHS_Nlinebreak_RHS_Nnewline_list), [T_LESSGREAT]=REDUCE(P_LHS_Nlinebreak_RHS_Nnewline_list), [T_DGEART]=REDUCE(P_LHS_Nlinebreak_RHS_Nnewline_list), [T_GREATAND]=REDUCE(P_LHS_Nlinebreak_RHS_Nnewline_list), [T_GREAT]=REDUCE(P_LHS_Nlinebreak_RHS_Nnewline_list), [T_LESSAND]=REDUCE(P_LHS_Nlinebreak_RHS_Nnewline_list), [T_LESS]=REDUCE(P_LHS_Nlinebreak_RHS_Nnewline_list), [T_BANG]=REDUCE(P_LHS_Nlinebreak_RHS_Nnewline_list), [T_IO_NUMBER]=REDUCE(P_LHS_Nlinebreak_RHS_Nnewline_list), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nlinebreak_RHS_Nnewline_list), [T_WORD]=REDUCE(P_LHS_Nlinebreak_RHS_Nnewline_list)},
/*  59 */	{[T_NEWLINE]=SHIFT(61), [T_EOF]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_DLESSDASH]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_DLESS]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_CLOBBER]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_LESSGREAT]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_DGEART]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_GREATAND]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_GREAT]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_LESSAND]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_LESS]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_BANG]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_IO_NUMBER]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_WORD]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS)},
/*  60 */	{[T_EOF]=REDUCE(P_LHS_Nnewline_list_RHS_TNEWLINE_Nnewline_list_PRIME), [T_DLESSDASH]=REDUCE(P_LHS_Nnewline_list_RHS_TNEWLINE_Nnewline_list_PRIME), [T_DLESS]=REDUCE(P_LHS_Nnewline_list_RHS_TNEWLINE_Nnewline_list_PRIME), [T_CLOBBER]=REDUCE(P_LHS_Nnewline_list_RHS_TNEWLINE_Nnewline_list_PRIME), [T_LESSGREAT]=REDUCE(P_LHS_Nnewline_list_RHS_TNEWLINE_Nnewline_list_PRIME), [T_DGEART]=REDUCE(P_LHS_Nnewline_list_RHS_TNEWLINE_Nnewline_list_PRIME), [T_GREATAND]=REDUCE(P_LHS_Nnewline_list_RHS_TNEWLINE_Nnewline_list_PRIME), [T_GREAT]=REDUCE(P_LHS_Nnewline_list_RHS_TNEWLINE_Nnewline_list_PRIME), [T_LESSAND]=REDUCE(P_LHS_Nnewline_list_RHS_TNEWLINE_Nnewline_list_PRIME), [T_LESS]=REDUCE(P_LHS_Nnewline_list_RHS_TNEWLINE_Nnewline_list_PRIME), [T_BANG]=REDUCE(P_LHS_Nnewline_list_RHS_TNEWLINE_Nnewline_list_PRIME), [T_IO_NUMBER]=REDUCE(P_LHS_Nnewline_list_RHS_TNEWLINE_Nnewline_list_PRIME), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nnewline_list_RHS_TNEWLINE_Nnewline_list_PRIME), [T_WORD]=REDUCE(P_LHS_Nnewline_list_RHS_TNEWLINE_Nnewline_list_PRIME)},
/*  61 */	{[T_NEWLINE]=SHIFT(61), [T_EOF]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_DLESSDASH]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_DLESS]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_CLOBBER]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_LESSGREAT]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_DGEART]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_GREATAND]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_GREAT]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_LESSAND]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_LESS]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_BANG]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_IO_NUMBER]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS), [T_WORD]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS)},
/*  62 */	{[T_EOF]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS_TNEWLINE_Nnewline_list_PRIME), [T_DLESSDASH]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS_TNEWLINE_Nnewline_list_PRIME), [T_DLESS]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS_TNEWLINE_Nnewline_list_PRIME), [T_CLOBBER]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS_TNEWLINE_Nnewline_list_PRIME), [T_LESSGREAT]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS_TNEWLINE_Nnewline_list_PRIME), [T_DGEART]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS_TNEWLINE_Nnewline_list_PRIME), [T_GREATAND]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS_TNEWLINE_Nnewline_list_PRIME), [T_GREAT]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS_TNEWLINE_Nnewline_list_PRIME), [T_LESSAND]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS_TNEWLINE_Nnewline_list_PRIME), [T_LESS]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS_TNEWLINE_Nnewline_list_PRIME), [T_BANG]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS_TNEWLINE_Nnewline_list_PRIME), [T_IO_NUMBER]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS_TNEWLINE_Nnewline_list_PRIME), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS_TNEWLINE_Nnewline_list_PRIME), [T_WORD]=REDUCE(P_LHS_Nnewline_list_PRIME_RHS_TNEWLINE_Nnewline_list_PRIME)},
/*  63 */	{[T_PIPE]=SHIFT(56), [T_EOF]=REDUCE(P_LHS_Npipe_sequence_PRIME_RHS), [T_OR_IF]=REDUCE(P_LHS_Npipe_sequence_PRIME_RHS), [T_AND_IF]=REDUCE(P_LHS_Npipe_sequence_PRIME_RHS), [T_SEMI]=REDUCE(P_LHS_Npipe_sequence_PRIME_RHS), [T_AMPER]=REDUCE(P_LHS_Npipe_sequence_PRIME_RHS), [T_NEWLINE]=REDUCE(P_LHS_Npipe_sequence_PRIME_RHS)},
/*  64 */	{[T_EOF]=REDUCE(P_LHS_Npipe_sequence_PRIME_RHS_TPIPE_Nlinebreak_Ncommand_Npipe_sequence_PRIME), [T_OR_IF]=REDUCE(P_LHS_Npipe_sequence_PRIME_RHS_TPIPE_Nlinebreak_Ncommand_Npipe_sequence_PRIME), [T_AND_IF]=REDUCE(P_LHS_Npipe_sequence_PRIME_RHS_TPIPE_Nlinebreak_Ncommand_Npipe_sequence_PRIME), [T_SEMI]=REDUCE(P_LHS_Npipe_sequence_PRIME_RHS_TPIPE_Nlinebreak_Ncommand_Npipe_sequence_PRIME), [T_AMPER]=REDUCE(P_LHS_Npipe_sequence_PRIME_RHS_TPIPE_Nlinebreak_Ncommand_Npipe_sequence_PRIME), [T_NEWLINE]=REDUCE(P_LHS_Npipe_sequence_PRIME_RHS_TPIPE_Nlinebreak_Ncommand_Npipe_sequence_PRIME)},
/*  65 */	{[T_EOF]=REDUCE(P_LHS_Nand_or_RHS_Npipeline_Nand_or_PRIME), [T_SEMI]=REDUCE(P_LHS_Nand_or_RHS_Npipeline_Nand_or_PRIME), [T_AMPER]=REDUCE(P_LHS_Nand_or_RHS_Npipeline_Nand_or_PRIME), [T_NEWLINE]=REDUCE(P_LHS_Nand_or_RHS_Npipeline_Nand_or_PRIME)},
/*  66 */	{[T_NEWLINE]=SHIFT(59), [T_DLESSDASH]=REDUCE(P_LHS_Nlinebreak_RHS), [T_DLESS]=REDUCE(P_LHS_Nlinebreak_RHS), [T_CLOBBER]=REDUCE(P_LHS_Nlinebreak_RHS), [T_LESSGREAT]=REDUCE(P_LHS_Nlinebreak_RHS), [T_DGEART]=REDUCE(P_LHS_Nlinebreak_RHS), [T_GREATAND]=REDUCE(P_LHS_Nlinebreak_RHS), [T_GREAT]=REDUCE(P_LHS_Nlinebreak_RHS), [T_LESSAND]=REDUCE(P_LHS_Nlinebreak_RHS), [T_LESS]=REDUCE(P_LHS_Nlinebreak_RHS), [T_BANG]=REDUCE(P_LHS_Nlinebreak_RHS), [T_IO_NUMBER]=REDUCE(P_LHS_Nlinebreak_RHS), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nlinebreak_RHS), [T_WORD]=REDUCE(P_LHS_Nlinebreak_RHS)},
/*  67 */	{[T_DLESSDASH]=REDUCE(P_LHS_Nand_or_op_RHS_TAND_IF), [T_DLESS]=REDUCE(P_LHS_Nand_or_op_RHS_TAND_IF), [T_CLOBBER]=REDUCE(P_LHS_Nand_or_op_RHS_TAND_IF), [T_LESSGREAT]=REDUCE(P_LHS_Nand_or_op_RHS_TAND_IF), [T_DGEART]=REDUCE(P_LHS_Nand_or_op_RHS_TAND_IF), [T_GREATAND]=REDUCE(P_LHS_Nand_or_op_RHS_TAND_IF), [T_GREAT]=REDUCE(P_LHS_Nand_or_op_RHS_TAND_IF), [T_LESSAND]=REDUCE(P_LHS_Nand_or_op_RHS_TAND_IF), [T_LESS]=REDUCE(P_LHS_Nand_or_op_RHS_TAND_IF), [T_BANG]=REDUCE(P_LHS_Nand_or_op_RHS_TAND_IF), [T_NEWLINE]=REDUCE(P_LHS_Nand_or_op_RHS_TAND_IF), [T_IO_NUMBER]=REDUCE(P_LHS_Nand_or_op_RHS_TAND_IF), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nand_or_op_RHS_TAND_IF), [T_WORD]=REDUCE(P_LHS_Nand_or_op_RHS_TAND_IF)},
/*  68 */	{[T_DLESSDASH]=REDUCE(P_LHS_Nand_or_op_RHS_TOR_IF), [T_DLESS]=REDUCE(P_LHS_Nand_or_op_RHS_TOR_IF), [T_CLOBBER]=REDUCE(P_LHS_Nand_or_op_RHS_TOR_IF), [T_LESSGREAT]=REDUCE(P_LHS_Nand_or_op_RHS_TOR_IF), [T_DGEART]=REDUCE(P_LHS_Nand_or_op_RHS_TOR_IF), [T_GREATAND]=REDUCE(P_LHS_Nand_or_op_RHS_TOR_IF), [T_GREAT]=REDUCE(P_LHS_Nand_or_op_RHS_TOR_IF), [T_LESSAND]=REDUCE(P_LHS_Nand_or_op_RHS_TOR_IF), [T_LESS]=REDUCE(P_LHS_Nand_or_op_RHS_TOR_IF), [T_BANG]=REDUCE(P_LHS_Nand_or_op_RHS_TOR_IF), [T_NEWLINE]=REDUCE(P_LHS_Nand_or_op_RHS_TOR_IF), [T_IO_NUMBER]=REDUCE(P_LHS_Nand_or_op_RHS_TOR_IF), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nand_or_op_RHS_TOR_IF), [T_WORD]=REDUCE(P_LHS_Nand_or_op_RHS_TOR_IF)},
/*  69 */	{[T_BANG]=SHIFT(6), [T_DLESSDASH]=REDUCE(P_LHS_Nbang_opt_RHS), [T_DLESS]=REDUCE(P_LHS_Nbang_opt_RHS), [T_CLOBBER]=REDUCE(P_LHS_Nbang_opt_RHS), [T_LESSGREAT]=REDUCE(P_LHS_Nbang_opt_RHS), [T_DGEART]=REDUCE(P_LHS_Nbang_opt_RHS), [T_GREATAND]=REDUCE(P_LHS_Nbang_opt_RHS), [T_GREAT]=REDUCE(P_LHS_Nbang_opt_RHS), [T_LESSAND]=REDUCE(P_LHS_Nbang_opt_RHS), [T_LESS]=REDUCE(P_LHS_Nbang_opt_RHS), [T_IO_NUMBER]=REDUCE(P_LHS_Nbang_opt_RHS), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nbang_opt_RHS), [T_WORD]=REDUCE(P_LHS_Nbang_opt_RHS)},
/*  70 */	{[T_OR_IF]=SHIFT(68), [T_AND_IF]=SHIFT(67), [T_EOF]=REDUCE(P_LHS_Nand_or_PRIME_RHS), [T_SEMI]=REDUCE(P_LHS_Nand_or_PRIME_RHS), [T_AMPER]=REDUCE(P_LHS_Nand_or_PRIME_RHS), [T_NEWLINE]=REDUCE(P_LHS_Nand_or_PRIME_RHS)},
/*  71 */	{[T_EOF]=REDUCE(P_LHS_Nand_or_PRIME_RHS_Nand_or_op_Nlinebreak_Npipeline_Nand_or_PRIME), [T_SEMI]=REDUCE(P_LHS_Nand_or_PRIME_RHS_Nand_or_op_Nlinebreak_Npipeline_Nand_or_PRIME), [T_AMPER]=REDUCE(P_LHS_Nand_or_PRIME_RHS_Nand_or_op_Nlinebreak_Npipeline_Nand_or_PRIME), [T_NEWLINE]=REDUCE(P_LHS_Nand_or_PRIME_RHS_Nand_or_op_Nlinebreak_Npipeline_Nand_or_PRIME)},
/*  72 */	{[T_EOF]=REDUCE(P_LHS_Nlist_RHS_Nand_or_Nlist_PRIME), [T_NEWLINE]=REDUCE(P_LHS_Nlist_RHS_Nand_or_Nlist_PRIME)},
/*  73 */	{[T_BANG]=SHIFT(6), [T_DLESSDASH]=REDUCE(P_LHS_Nbang_opt_RHS), [T_DLESS]=REDUCE(P_LHS_Nbang_opt_RHS), [T_CLOBBER]=REDUCE(P_LHS_Nbang_opt_RHS), [T_LESSGREAT]=REDUCE(P_LHS_Nbang_opt_RHS), [T_DGEART]=REDUCE(P_LHS_Nbang_opt_RHS), [T_GREATAND]=REDUCE(P_LHS_Nbang_opt_RHS), [T_GREAT]=REDUCE(P_LHS_Nbang_opt_RHS), [T_LESSAND]=REDUCE(P_LHS_Nbang_opt_RHS), [T_LESS]=REDUCE(P_LHS_Nbang_opt_RHS), [T_IO_NUMBER]=REDUCE(P_LHS_Nbang_opt_RHS), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nbang_opt_RHS), [T_WORD]=REDUCE(P_LHS_Nbang_opt_RHS), [T_EOF]=REDUCE(P_LHS_Nlist_PRIME_PRIME_RHS), [T_NEWLINE]=REDUCE(P_LHS_Nlist_PRIME_PRIME_RHS)},
/*  74 */	{[T_EOF]=REDUCE(P_LHS_Nseparator_op_RHS_TAMPER), [T_DLESSDASH]=REDUCE(P_LHS_Nseparator_op_RHS_TAMPER), [T_DLESS]=REDUCE(P_LHS_Nseparator_op_RHS_TAMPER), [T_CLOBBER]=REDUCE(P_LHS_Nseparator_op_RHS_TAMPER), [T_LESSGREAT]=REDUCE(P_LHS_Nseparator_op_RHS_TAMPER), [T_DGEART]=REDUCE(P_LHS_Nseparator_op_RHS_TAMPER), [T_GREATAND]=REDUCE(P_LHS_Nseparator_op_RHS_TAMPER), [T_GREAT]=REDUCE(P_LHS_Nseparator_op_RHS_TAMPER), [T_LESSAND]=REDUCE(P_LHS_Nseparator_op_RHS_TAMPER), [T_LESS]=REDUCE(P_LHS_Nseparator_op_RHS_TAMPER), [T_BANG]=REDUCE(P_LHS_Nseparator_op_RHS_TAMPER), [T_NEWLINE]=REDUCE(P_LHS_Nseparator_op_RHS_TAMPER), [T_IO_NUMBER]=REDUCE(P_LHS_Nseparator_op_RHS_TAMPER), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nseparator_op_RHS_TAMPER), [T_WORD]=REDUCE(P_LHS_Nseparator_op_RHS_TAMPER)},
/*  75 */	{[T_EOF]=REDUCE(P_LHS_Nseparator_op_RHS_TSEMI), [T_DLESSDASH]=REDUCE(P_LHS_Nseparator_op_RHS_TSEMI), [T_DLESS]=REDUCE(P_LHS_Nseparator_op_RHS_TSEMI), [T_CLOBBER]=REDUCE(P_LHS_Nseparator_op_RHS_TSEMI), [T_LESSGREAT]=REDUCE(P_LHS_Nseparator_op_RHS_TSEMI), [T_DGEART]=REDUCE(P_LHS_Nseparator_op_RHS_TSEMI), [T_GREATAND]=REDUCE(P_LHS_Nseparator_op_RHS_TSEMI), [T_GREAT]=REDUCE(P_LHS_Nseparator_op_RHS_TSEMI), [T_LESSAND]=REDUCE(P_LHS_Nseparator_op_RHS_TSEMI), [T_LESS]=REDUCE(P_LHS_Nseparator_op_RHS_TSEMI), [T_BANG]=REDUCE(P_LHS_Nseparator_op_RHS_TSEMI), [T_NEWLINE]=REDUCE(P_LHS_Nseparator_op_RHS_TSEMI), [T_IO_NUMBER]=REDUCE(P_LHS_Nseparator_op_RHS_TSEMI), [T_ASSIGNEMENT_WORD]=REDUCE(P_LHS_Nseparator_op_RHS_TSEMI), [T_WORD]=REDUCE(P_LHS_Nseparator_op_RHS_TSEMI)},
/*  76 */	{[T_EOF]=REDUCE(P_LHS_Nlist_PRIME_RHS_Nseparator_op_Nlist_PRIME_PRIME), [T_NEWLINE]=REDUCE(P_LHS_Nlist_PRIME_RHS_Nseparator_op_Nlist_PRIME_PRIME)},
/*  77 */	{[T_SEMI]=SHIFT(75), [T_AMPER]=SHIFT(74), [T_EOF]=REDUCE(P_LHS_Nlist_PRIME_RHS), [T_NEWLINE]=REDUCE(P_LHS_Nlist_PRIME_RHS)},
/*  78 */	{[T_EOF]=REDUCE(P_LHS_Nlist_PRIME_PRIME_RHS_Nand_or_Nlist_PRIME), [T_NEWLINE]=REDUCE(P_LHS_Nlist_PRIME_PRIME_RHS_Nand_or_Nlist_PRIME)},
/*  79 */	{[T_EOF]=REDUCE(P_LHS_Ncomplete_command_RHS_Nlist_Nlinebreak)},
};

static int
shell_lr_goto_table[80][TOTAL_NTER] = {
/*   0 */	{[N_bang_opt]=GOTO(5), [N_pipeline]=GOTO(4), [N_and_or]=GOTO(3), [N_list]=GOTO(2), [N_complete_command]=GOTO(1)},
/*   1 */	{},
/*   2 */	{[N_newline_list]=GOTO(58), [N_linebreak]=GOTO(79)},
/*   3 */	{[N_separator_op]=GOTO(73), [N_list_PRIME]=GOTO(72)},
/*   4 */	{[N_and_or_op]=GOTO(66), [N_and_or_PRIME]=GOTO(65)},
/*   5 */	{[N_io_number_opt]=GOTO(13), [N_io_redirect]=GOTO(11), [N_cmd_prefix]=GOTO(9), [N_command]=GOTO(8), [N_pipe_sequence]=GOTO(7)},
/*   6 */	{},
/*   7 */	{},
/*   8 */	{[N_pipe_sequence_PRIME]=GOTO(55)},
/*   9 */	{[N_command_suffix]=GOTO(52)},
/*  10 */	{[N_io_number_opt]=GOTO(13), [N_io_redirect]=GOTO(44), [N_cmd_suffix]=GOTO(43), [N_cmd_suffix_opt]=GOTO(42)},
/*  11 */	{[N_io_redirect]=GOTO(36), [N_cmd_prefix_PRIME]=GOTO(41), [N_io_number_opt]=GOTO(13)},
/*  12 */	{[N_cmd_prefix_PRIME]=GOTO(38), [N_io_redirect]=GOTO(36), [N_io_number_opt]=GOTO(13)},
/*  13 */	{[N_io_here]=GOTO(17), [N_io_file]=GOTO(16), [N_io_kind]=GOTO(15)},
/*  14 */	{},
/*  15 */	{},
/*  16 */	{},
/*  17 */	{},
/*  18 */	{},
/*  19 */	{},
/*  20 */	{},
/*  21 */	{},
/*  22 */	{},
/*  23 */	{},
/*  24 */	{},
/*  25 */	{},
/*  26 */	{},
/*  27 */	{},
/*  28 */	{},
/*  29 */	{},
/*  30 */	{},
/*  31 */	{},
/*  32 */	{},
/*  33 */	{},
/*  34 */	{},
/*  35 */	{},
/*  36 */	{[N_cmd_prefix_PRIME]=GOTO(40), [N_io_redirect]=GOTO(36), [N_io_number_opt]=GOTO(13)},
/*  37 */	{[N_cmd_prefix_PRIME]=GOTO(39), [N_io_redirect]=GOTO(36), [N_io_number_opt]=GOTO(13)},
/*  38 */	{},
/*  39 */	{},
/*  40 */	{},
/*  41 */	{},
/*  42 */	{},
/*  43 */	{},
/*  44 */	{[N_io_redirect]=GOTO(46), [N_cmd_suffix_PRIME]=GOTO(51), [N_io_number_opt]=GOTO(13)},
/*  45 */	{[N_cmd_suffix_PRIME]=GOTO(48), [N_io_redirect]=GOTO(46), [N_io_number_opt]=GOTO(13)},
/*  46 */	{[N_cmd_suffix_PRIME]=GOTO(50), [N_io_redirect]=GOTO(46), [N_io_number_opt]=GOTO(13)},
/*  47 */	{[N_cmd_suffix_PRIME]=GOTO(49), [N_io_redirect]=GOTO(46), [N_io_number_opt]=GOTO(13)},
/*  48 */	{},
/*  49 */	{},
/*  50 */	{},
/*  51 */	{},
/*  52 */	{},
/*  53 */	{[N_cmd_suffix_opt]=GOTO(54), [N_io_number_opt]=GOTO(13), [N_io_redirect]=GOTO(44), [N_cmd_suffix]=GOTO(43)},
/*  54 */	{},
/*  55 */	{},
/*  56 */	{[N_newline_list]=GOTO(58), [N_linebreak]=GOTO(57)},
/*  57 */	{[N_command]=GOTO(63), [N_io_number_opt]=GOTO(13), [N_io_redirect]=GOTO(11), [N_cmd_prefix]=GOTO(9)},
/*  58 */	{},
/*  59 */	{[N_newline_list_PRIME]=GOTO(60)},
/*  60 */	{},
/*  61 */	{[N_newline_list_PRIME]=GOTO(62)},
/*  62 */	{},
/*  63 */	{[N_pipe_sequence_PRIME]=GOTO(64)},
/*  64 */	{},
/*  65 */	{},
/*  66 */	{[N_newline_list]=GOTO(58), [N_linebreak]=GOTO(69)},
/*  67 */	{},
/*  68 */	{},
/*  69 */	{[N_pipeline]=GOTO(70), [N_bang_opt]=GOTO(5)},
/*  70 */	{[N_and_or_PRIME]=GOTO(71), [N_and_or_op]=GOTO(66)},
/*  71 */	{},
/*  72 */	{},
/*  73 */	{[N_and_or]=GOTO(77), [N_list_PRIME_PRIME]=GOTO(76), [N_bang_opt]=GOTO(5), [N_pipeline]=GOTO(4)},
/*  74 */	{},
/*  75 */	{},
/*  76 */	{},
/*  77 */	{[N_list_PRIME]=GOTO(78), [N_separator_op]=GOTO(73)},
/*  78 */	{},
/*  79 */	{},
};

#endif

static int
shell_sync_token[TOTAL_NTER][20] = {
	[N_complete_command] = { T_EOF, -1 },
	[N_list] = { T_NEWLINE, T_EOF, -1 },
	[N_linebreak] = { T_WORD, T_ASSIGNEMENT_WORD, T_IO_NUMBER, T_BANG, T_LESS, T_LESSAND, T_GREAT, T_GREATAND, T_DGEART, T_LESSGREAT, T_CLOBBER, T_DLESS, T_DLESSDASH, T_EOF, -1 },
	[N_and_or] = { T_NEWLINE, T_AMPER, T_SEMI, T_EOF, -1 },
	[N_list_PRIME] = { T_NEWLINE, T_EOF, -1 },
	[N_separator_op] = { T_WORD, T_ASSIGNEMENT_WORD, T_IO_NUMBER, T_NEWLINE, T_BANG, T_LESS, T_LESSAND, T_GREAT, T_GREATAND, T_DGEART, T_LESSGREAT, T_CLOBBER, T_DLESS, T_DLESSDASH, T_EOF, -1 },
	[N_list_PRIME_PRIME] = { T_NEWLINE, T_EOF, -1 },
	[N_pipeline] = { T_NEWLINE, T_AMPER, T_SEMI, T_AND_IF, T_OR_IF, T_EOF, -1 },
	[N_and_or_PRIME] = { T_NEWLINE, T_AMPER, T_SEMI, T_EOF, -1 },
	[N_and_or_op] = { T_WORD, T_ASSIGNEMENT_WORD, T_IO_NUMBER, T_NEWLINE, T_BANG, T_LESS, T_LESSAND, T_GREAT, T_GREATAND, T_DGEART, T_LESSGREAT, T_CLOBBER, T_DLESS, T_DLESSDASH, -1 },
	[N_bang_opt] = { T_WORD, T_ASSIGNEMENT_WORD, T_IO_NUMBER, T_LESS, T_LESSAND, T_GREAT, T_GREATAND, T_DGEART, T_LESSGREAT, T_CLOBBER, T_DLESS, T_DLESSDASH, -1 },
	[N_pipe_sequence] = { T_NEWLINE, T_AMPER, T_SEMI, T_AND_IF, T_OR_IF, T_EOF, -1 },
	[N_command] = { T_NEWLINE, T_AMPER, T_SEMI, T_AND_IF, T_OR_IF, T_PIPE, T_EOF, -1 },
	[N_pipe_sequence_PRIME] = { T_NEWLINE, T_AMPER, T_SEMI, T_AND_IF, T_OR_IF, T_EOF, -1 },
	[N_cmd_prefix] = { T_WORD, T_NEWLINE, T_AMPER, T_SEMI, T_AND_IF, T_OR_IF, T_PIPE, T_EOF, -1 },
	[N_command_suffix] = { T_NEWLINE, T_AMPER, T_SEMI, T_AND_IF, T_OR_IF, T_PIPE, T_EOF, -1 },
	[N_cmd_suffix_opt] = { T_NEWLINE, T_AMPER, T_SEMI, T_AND_IF, T_OR_IF, T_PIPE, T_EOF, -1 },
	[N_cmd_suffix] = { T_NEWLINE, T_AMPER, T_SEMI, T_AND_IF, T_OR_IF, T_PIPE, T_EOF, -1 },
	[N_io_redirect] = { T_WORD, T_ASSIGNEMENT_WORD, T_IO_NUMBER, T_NEWLINE, T_AMPER, T_SEMI, T_AND_IF, T_OR_IF, T_PIPE, T_LESS, T_LESSAND, T_GREAT, T_GREATAND, T_DGEART, T_LESSGREAT, T_CLOBBER, T_DLESS, T_DLESSDASH, T_EOF, -1 },
	[N_cmd_suffix_PRIME] = { T_NEWLINE, T_AMPER, T_SEMI, T_AND_IF, T_OR_IF, T_PIPE, T_EOF, -1 },
	[N_cmd_prefix_PRIME] = { T_WORD, T_NEWLINE, T_AMPER, T_SEMI, T_AND_IF, T_OR_IF, T_PIPE, T_EOF, -1 },
	[N_io_number_opt] = { T_LESS, T_LESSAND, T_GREAT, T_GREATAND, T_DGEART, T_LESSGREAT, T_CLOBBER, T_DLESS, T_DLESSDASH, -1 },
	[N_io_kind] = { T_WORD, T_ASSIGNEMENT_WORD, T_IO_NUMBER, T_NEWLINE, T_AMPER, T_SEMI, T_AND_IF, T_OR_IF, T_PIPE, T_LESS, T_LESSAND, T_GREAT, T_GREATAND, T_DGEART, T_LESSGREAT, T_CLOBBER, T_DLESS, T_DLESSDASH, T_EOF, -1 },
	[N_io_file] = { T_WORD, T_ASSIGNEMENT_WORD, T_IO_NUMBER, T_NEWLINE, T_AMPER, T_SEMI, T_AND_IF, T_OR_IF, T_PIPE, T_LESS, T_LESSAND, T_GREAT, T_GREATAND, T_DGEART, T_LESSGREAT, T_CLOBBER, T_DLESS, T_DLESSDASH, T_EOF, -1 },
	[N_io_here] = { T_WORD, T_ASSIGNEMENT_WORD, T_IO_NUMBER, T_NEWLINE, T_AMPER, T_SEMI, T_AND_IF, T_OR_IF, T_PIPE, T_LESS, T_LESSAND, T_GREAT, T_GREATAND, T_DGEART, T_LESSGREAT, T_CLOBBER, T_DLESS, T_DLESSDASH, T_EOF, -1 },
	[N_newline_list] = { T_WORD, T_ASSIGNEMENT_WORD, T_IO_NUMBER, T_BANG, T_LESS, T_LESSAND, T_GREAT, T_GREATAND, T_DGEART, T_LESSGREAT, T_CLOBBER, T_DLESS, T_DLESSDASH, T_EOF, -1 },
	[N_newline_list_PRIME] = { T_WORD, T_ASSIGNEMENT_WORD, T_IO_NUMBER, T_BANG, T_LESS, T_LESSAND, T_GREAT, T_GREATAND, T_DGEART, T_LESSGREAT, T_CLOBBER, T_DLESS, T_DLESSDASH, T_EOF, -1 },
};

#endif /* _SHELL_GRM_H_ */
